!======================================================================================================================!
!
!                    DassFlow1D Version 2.1
!
!======================================================================================================================!
!
!  Copyright University of Toulouse-INSA - CNRS (France)
!
!  This file is part of the DassFlow software (Data Assimilation for Free Surface Flows).
!  DassFlow is a computational software aiming at simulating geophysical free surface flows.
!  It is designed for Variational Data Assimilation (4D-var) and sensitivity analyses. 
! Inverse capabilities are based on the adjoint code which is generated by 
! a source-to-source algorithmic differentiation (Tapenade software used).
!
!  DassFlow software includes few mostly independent "modules" with common architectures and structures:
!    - DassFlow 2DShallow (shallow water equations in (h,q), finite volumes), i.e. the present code.
!    - DassFlow3D  (non-linear Stokes equations, finite elements, mobile geometries, ALE).
!    - DassFlow 1D (shallow water equations in (S,Q), finite volumes or finite differences), river hydraulics.
!  Please consult the DassFlow webpage for more details: http://www.math.univ-toulouse.fr/DassFlow
!
! You have used DassFlow in an article, a scientific document etc ?  How to cite us ? Please consult the webpage.
! 
!  Many people have contributed to the DassFlow developments from the initial version to the latest ones.
!  Current main developers or scientific contributers are:
!               P. Brisset (CNES & Mathematics Institute of Toulouse & INSA Toulouse)
!               F. Couderc (CNRS & Mathematics Institute of Toulouse IMT)
!               P.-A. Garambois (INSA & ICUBE Strasbourg)
!               J. Monnier (INSA & Mathematics Institute of Toulouse IMT).
!               J.-P. Vila (INSA & Mathematics Institute of Toulouse IMT).
!  and former other developers (R. Madec, M. Honnorat and J. Marin).
!
!  Scientific contact : jerome.monnier@insa-toulouse.fr
!  Technical  contacts : frederic.couderc@math.univ-toulouse.fr, pierre.brisset@insa-toulouse.fr
!
!  This software is governed by the CeCILL license under French law and abiding by the rules of distribution
!  of free software. You can use, modify and/or redistribute the software under the terms of the CeCILL license
!  as circulated by CEA, CNRS and INRIA at the following URL: "http://www.cecill.info".
!
!  As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the
!  license, users are provided only with a limited warranty and the software's author, the holder of the economic
!  rights, and the successive licensors have only limited liability.
!
!  In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or
!  developing or reproducing the software by the user in light of its specific status of free software, that may
!  mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and
!  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the
!  software's suitability as regards their requirements in conditions enabling the security of their systems and/or
!  data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
!
!  The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you
!  accept its terms.
!
!======================================================================================================================!
!> \file m_mesh.f90
!! \brief This file includes m_mesh module.
!! \details The file includes only m_mesh module (see doc m_mesh module).

!**********************************************************************************************************************!
!**********************************************************************************************************************!
!
!  Module m_mesh
!
!**********************************************************************************************************************!
!**********************************************************************************************************************!





!> Module m_mesh.
!!
!! \details This module includes mesh, cross section and point structure and subroutine alloc/deallocation of the
!! cross section
module mwd_mesh_hy

    use md_constant !% only: sp

    implicit none
    
    !> Structure of a cross section.
    type Crosssection
        
        !> Planar coordinates
        real(sp), dimension(2) :: coord
        !> Curvilinear abscissa (x(i) where i is the index of this cross-section in the space discretization)
        real(sp) :: x
        !> Indices of overbanks levels (1=left, 2=right)
        integer, dimension(2) :: ob_levels
        !> Bathymetry height
        real(sp) :: bathy
        !> Distance between x(i-1/2) and x(i+1/2)
        real(sp) :: delta
        !> Distance between x(i-1) and x(i)
        real(sp) :: deltademi
        !> Array of Strickler parameters
        real(sp), dimension(:), allocatable :: strickler_params
        !---------------------------------------------------------------------------------------------------------------
        ! FOLLOWING VARIABLES ARE RELATED TO THE TRAPEZOIDAL DISCRETIZATION OF CROSS-SECTION SHAPE. CAN BE REPLACED BY
        ! A SIMPLER DISCRETIZATION (1 TRIANGLE, 2 RECTANGLES, ETC.) OR THE STANDARD DISCRETIZATION Z(Y) WHERE Y IS THE
        ! TANGENTIAL COORDINATE
        !---------------------------------------------------------------------------------------------------------------
        !> Number of discretization levels
        integer :: nlevels
        !> Array of levels heights
        real(sp), dimension(:), allocatable :: level_heights
        !> Array of levels widths
        real(sp), dimension(:), allocatable :: level_widths
        !> Array of displacements of center
        real(sp), dimension(:), allocatable :: y

    end type Crosssection


    !> Structure of a segment.
    type Segment
                
        !> Index of first cross-section
        integer :: first_cs
        !> Index of last cross-section
        integer :: last_cs
        !> Indices of downstream segments
        integer, dimension(:), allocatable :: ds_seg
        !> Indices of upstream segments
        integer, dimension(:), allocatable :: us_seg
        !> Index of downstream BC (only for a segment with no downstream segment)
        integer :: ds_bc
        !> Index of upstream BC (only for a segment with no upstream segments)
        integer :: us_bc

    end type Segment


    !> Structure of a mesh.
    type Mesh
                
        !> Number of cross-sections
        integer :: ncs
        !> Number of segments
        integer :: nseg
        !> Array of cross-sections
        type(Crosssection), dimension(:), allocatable :: cs
        !> Array of segments
        type(Segment), dimension(:), allocatable :: seg

    end type Mesh

contains

    subroutine Crosssection_initialise(this, nlevels)

        implicit none

        type(Crosssection), intent(inout) :: this
        integer, intent(in) :: nlevels

        this%nlevels = nlevels

        allocate(this%strickler_params(this%nlevels))
        allocate(this%level_heights(this%nlevels))
        allocate(this%level_widths(this%nlevels))
        allocate(this%y(this%nlevels))

    end subroutine Crosssection_initialise

    subroutine Segment_initialise(this, nseg)

        implicit none

        type(Segment), intent(inout) :: this
        integer, intent(in) :: nseg

        allocate(this%ds_seg(nseg))
        allocate(this%us_seg(nseg))

    end subroutine Segment_initialise

    subroutine Mesh_initialise(this, ncs, nseg, nlevels)

        implicit none

        type(Mesh), intent(inout) :: this
        integer, intent(in) :: ncs, nseg
        integer, dimension(ncs), intent(in) :: nlevels

        integer :: i

        this%ncs = ncs
        this%nseg = nseg

        allocate(this%seg(this%nseg))

        do i = 1, this%nseg
            call Segment_initialise(this%seg(i), this%nseg)
        end do

        allocate(this%cs(this%ncs))
        
        do i = 1, this%ncs
            call Crosssection_initialise(this%cs(i), nlevels(i))
        end do

    end subroutine Mesh_initialise

end module mwd_mesh_hy


! design d'un prmier reseau hydrog avec cross section simplifie:
! prpepro --> rese vect qui permet d'alimenter le type segment
! prpepro + loi geomorpho w = f(A) permet d'alimenter le type section et indice first and last section