name: smash
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    
    # compile
    - make
    - gcc
    - gfortran

    # required dependencies
    - numpy>=1.13
    - f90wrap
    - rasterio
    - pandas
    - h5py
    - tqdm
    - scipy
    - pyyaml
    - terminaltables
    - matplotlib  # (optional: only used for plotting and visualization)
