!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!%      This module `mwd_parameters` encapsulates all SMASH parameters.
!%      This module is wrapped and differentiated.
!%
!%      ParametersDT type:
!%      
!%      </> Public
!%      ======================== =======================================
!%      `Variables`              Description
!%      ======================== =======================================
!%      ``ci``                   Interception parameter          [mm]    (default: 1)     ]0, +Inf[
!%      ``cp``                   Production parameter            [mm]    (default: 200)   ]0, +Inf[
!%      ``beta``                 Percolation parameter           [-]     (default: 1000)  ]0, +Inf[
!%      ``cft``                  Fast transfer parameter         [mm]    (default: 500)   ]0, +Inf[
!%      ``cst``                  Slow transfer parameter         [mm]    (default: 500)   ]0, +Inf[
!%      ``alpha``                Transfer partitioning parameter [-]     (default: 0.9)   ]0, 1[
!%      ``exc``                  Exchange parameter              [mm/dt] (default: 0)     ]-Inf, +Inf[
!%      ``lr``                   Linear routing parameter        [min]   (default: 5)     ]0, +Inf[
!%      ======================== =======================================
!%
!%      contains
!%
!%      [1] ParametersDT_initialise
!%      [2] parameters_copy
!%      [3] parameters_to_matrix
!%      [4] matrix_to_parameters
!%      [5] vector_to_parameters
!%      [6] set0_parameters
MODULE MWD_PARAMETERS_DIFF_B
!% only: sp, dp, lchar, np, ns
  USE MWD_COMMON
!% only: MeshDT
  USE MWD_MESH
  IMPLICIT NONE
  TYPE PARAMETERSDT
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: ci
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: cp
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: beta
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: cft
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: cst
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: alpha
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: exc
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: lr
  END TYPE PARAMETERSDT

CONTAINS
  SUBROUTINE PARAMETERSDT_INITIALISE(parameters, mesh)
    IMPLICIT NONE
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    INTEGER :: nrow, ncol
    nrow = mesh%nrow
    ncol = mesh%ncol
    ALLOCATE(parameters%ci(nrow, ncol))
    ALLOCATE(parameters%cp(nrow, ncol))
    ALLOCATE(parameters%beta(nrow, ncol))
    ALLOCATE(parameters%cft(nrow, ncol))
    ALLOCATE(parameters%cst(nrow, ncol))
    ALLOCATE(parameters%alpha(nrow, ncol))
    ALLOCATE(parameters%exc(nrow, ncol))
    ALLOCATE(parameters%lr(nrow, ncol))
    parameters%ci = 1._sp
    parameters%cp = 200._sp
    parameters%beta = 1000._sp
    parameters%cft = 500._sp
    parameters%cst = 500._sp
    parameters%alpha = 0.9_sp
    parameters%exc = 0._sp
    parameters%lr = 5._sp
  END SUBROUTINE PARAMETERSDT_INITIALISE

!%      TODO comment  
  SUBROUTINE PARAMETERS_COPY(parameters_in, parameters_out)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters_in
    TYPE(PARAMETERSDT), INTENT(OUT) :: parameters_out
    parameters_out = parameters_in
  END SUBROUTINE PARAMETERS_COPY

!  Differentiation of parameters_to_matrix in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: matrix
!   with respect to varying inputs: *(parameters.ci) *(parameters.cp)
!                *(parameters.beta) *(parameters.cft) *(parameters.cst)
!                *(parameters.alpha) *(parameters.exc) *(parameters.lr)
!   Plus diff mem management of: parameters.ci:in parameters.cp:in
!                parameters.beta:in parameters.cft:in parameters.cst:in
!                parameters.alpha:in parameters.exc:in parameters.lr:in
!%      TODO comment  
  SUBROUTINE PARAMETERS_TO_MATRIX_B(parameters, parameters_b, matrix, &
&   matrix_b)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters
    TYPE(PARAMETERSDT) :: parameters_b
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(parameters%cp, 1), SIZE(parameters%cp, 2), &
&   np), INTENT(INOUT) :: matrix
    REAL(sp), DIMENSION(SIZE(parameters%cp, 1), SIZE(parameters%cp, 2), &
&   np), INTENT(INOUT) :: matrix_b
    parameters_b%lr = 0.0_4
    parameters_b%lr = parameters_b%lr + matrix_b(:, :, 8)
    matrix_b(:, :, 8) = 0.0_4
    parameters_b%exc = 0.0_4
    parameters_b%exc = parameters_b%exc + matrix_b(:, :, 7)
    matrix_b(:, :, 7) = 0.0_4
    parameters_b%alpha = 0.0_4
    parameters_b%alpha = parameters_b%alpha + matrix_b(:, :, 6)
    matrix_b(:, :, 6) = 0.0_4
    parameters_b%cst = 0.0_4
    parameters_b%cst = parameters_b%cst + matrix_b(:, :, 5)
    matrix_b(:, :, 5) = 0.0_4
    parameters_b%cft = 0.0_4
    parameters_b%cft = parameters_b%cft + matrix_b(:, :, 4)
    matrix_b(:, :, 4) = 0.0_4
    parameters_b%beta = 0.0_4
    parameters_b%beta = parameters_b%beta + matrix_b(:, :, 3)
    matrix_b(:, :, 3) = 0.0_4
    parameters_b%cp = 0.0_4
    parameters_b%cp = parameters_b%cp + matrix_b(:, :, 2)
    matrix_b(:, :, 2) = 0.0_4
    parameters_b%ci = 0.0_4
    parameters_b%ci = parameters_b%ci + matrix_b(:, :, 1)
  END SUBROUTINE PARAMETERS_TO_MATRIX_B

!%      TODO comment  
  SUBROUTINE PARAMETERS_TO_MATRIX(parameters, matrix)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(parameters%cp, 1), SIZE(parameters%cp, 2), &
&   np), INTENT(INOUT) :: matrix
    matrix(:, :, 1) = parameters%ci(:, :)
    matrix(:, :, 2) = parameters%cp(:, :)
    matrix(:, :, 3) = parameters%beta(:, :)
    matrix(:, :, 4) = parameters%cft(:, :)
    matrix(:, :, 5) = parameters%cst(:, :)
    matrix(:, :, 6) = parameters%alpha(:, :)
    matrix(:, :, 7) = parameters%exc(:, :)
    matrix(:, :, 8) = parameters%lr(:, :)
  END SUBROUTINE PARAMETERS_TO_MATRIX

!%      TODO comment  
  SUBROUTINE MATRIX_TO_PARAMETERS(matrix, parameters)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(parameters%cp, 1), SIZE(parameters%cp, 2), &
&   np), INTENT(IN) :: matrix
    parameters%ci(:, :) = matrix(:, :, 1)
    parameters%cp(:, :) = matrix(:, :, 2)
    parameters%beta(:, :) = matrix(:, :, 3)
    parameters%cft(:, :) = matrix(:, :, 4)
    parameters%cst(:, :) = matrix(:, :, 5)
    parameters%alpha(:, :) = matrix(:, :, 6)
    parameters%exc(:, :) = matrix(:, :, 7)
    parameters%lr(:, :) = matrix(:, :, 8)
  END SUBROUTINE MATRIX_TO_PARAMETERS

!%      TODO comment  
  SUBROUTINE VECTOR_TO_PARAMETERS(vector, parameters)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    REAL(sp), DIMENSION(np), INTENT(IN) :: vector
    parameters%ci = vector(1)
    parameters%cp = vector(2)
    parameters%beta = vector(3)
    parameters%cft = vector(4)
    parameters%cst = vector(5)
    parameters%alpha = vector(6)
    parameters%exc = vector(7)
    parameters%lr = vector(8)
  END SUBROUTINE VECTOR_TO_PARAMETERS

!%      TODO comment  
  SUBROUTINE SET0_PARAMETERS(parameters)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    REAL(sp), DIMENSION(np) :: vector0
    vector0 = 0._sp
    CALL VECTOR_TO_PARAMETERS(vector0, parameters)
  END SUBROUTINE SET0_PARAMETERS

END MODULE MWD_PARAMETERS_DIFF_B

!%      This module `mwd_states` encapsulates all SMASH states.
!%      This module is wrapped and differentiated.
!%
!%      StatesDT type:
!%      
!%      </> Public
!%      ======================== =======================================
!%      `Variables`              Description
!%      ======================== =======================================
!%      ``hi``                   Interception state    [-]   (default: 0.01)   ]0, 1[
!%      ``hp``                   Production state      [-]   (default: 0.01)   ]0, 1[
!%      ``hft``                  Fast transfer state   [-]   (default: 0.01)   ]0, 1[
!%      ``hst``                  Slow transfer state   [-]   (default: 0.01)   ]0, 1[
!%      ``hlr``                  Linear routing state  [mm]  (default: 0.01)   ]0, +Inf[
!%      ======================== =======================================
!%
!%      contains
!%
!%      [1] StatesDT_initialise
!%      [2] states_copy
!%      [3] states_to_matrix
!%      [4] matrix_to_states
!%      [5] vector_to_states
!%      [6] set0_states
MODULE MWD_STATES_DIFF_B
!% only: sp, dp, lchar, np, ns
  USE MWD_COMMON
!% only: MeshDT
  USE MWD_MESH
  IMPLICIT NONE
  TYPE STATESDT
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: hi
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: hp
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: hft
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: hst
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: hlr
  END TYPE STATESDT

CONTAINS
  SUBROUTINE STATESDT_INITIALISE(states, mesh)
    IMPLICIT NONE
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(STATESDT), INTENT(INOUT) :: states
    INTEGER :: nrow, ncol
    nrow = mesh%nrow
    ncol = mesh%ncol
    ALLOCATE(states%hi(nrow, ncol))
    ALLOCATE(states%hp(nrow, ncol))
    ALLOCATE(states%hft(nrow, ncol))
    ALLOCATE(states%hst(nrow, ncol))
    ALLOCATE(states%hlr(nrow, ncol))
    states%hi = 0.01_sp
    states%hp = 0.01_sp
    states%hft = 0.01_sp
    states%hst = 0.01_sp
    states%hlr = 0.01_sp
  END SUBROUTINE STATESDT_INITIALISE

!%      TODO comment       
  SUBROUTINE STATES_COPY(states_in, states_out)
    IMPLICIT NONE
    TYPE(STATESDT), INTENT(IN) :: states_in
    TYPE(STATESDT), INTENT(OUT) :: states_out
    states_out = states_in
  END SUBROUTINE STATES_COPY

!  Differentiation of states_to_matrix in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: matrix
!   with respect to varying inputs: *(states.hi) *(states.hp) *(states.hft)
!                *(states.hst) *(states.hlr)
!   Plus diff mem management of: states.hi:in states.hp:in states.hft:in
!                states.hst:in states.hlr:in
!%      TODO comment 
  SUBROUTINE STATES_TO_MATRIX_B(states, states_b, matrix, matrix_b)
    IMPLICIT NONE
    TYPE(STATESDT), INTENT(IN) :: states
    TYPE(STATESDT) :: states_b
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(states%hp, 1), SIZE(states%hp, 2), ns), &
&   INTENT(INOUT) :: matrix
    REAL(sp), DIMENSION(SIZE(states%hp, 1), SIZE(states%hp, 2), ns), &
&   INTENT(INOUT) :: matrix_b
    states_b%hlr = 0.0_4
    states_b%hlr = states_b%hlr + matrix_b(:, :, 5)
    matrix_b(:, :, 5) = 0.0_4
    states_b%hst = 0.0_4
    states_b%hst = states_b%hst + matrix_b(:, :, 4)
    matrix_b(:, :, 4) = 0.0_4
    states_b%hft = 0.0_4
    states_b%hft = states_b%hft + matrix_b(:, :, 3)
    matrix_b(:, :, 3) = 0.0_4
    states_b%hp = 0.0_4
    states_b%hp = states_b%hp + matrix_b(:, :, 2)
    matrix_b(:, :, 2) = 0.0_4
    states_b%hi = 0.0_4
    states_b%hi = states_b%hi + matrix_b(:, :, 1)
  END SUBROUTINE STATES_TO_MATRIX_B

!%      TODO comment 
  SUBROUTINE STATES_TO_MATRIX(states, matrix)
    IMPLICIT NONE
    TYPE(STATESDT), INTENT(IN) :: states
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(states%hp, 1), SIZE(states%hp, 2), ns), &
&   INTENT(INOUT) :: matrix
    matrix(:, :, 1) = states%hi(:, :)
    matrix(:, :, 2) = states%hp(:, :)
    matrix(:, :, 3) = states%hft(:, :)
    matrix(:, :, 4) = states%hst(:, :)
    matrix(:, :, 5) = states%hlr(:, :)
  END SUBROUTINE STATES_TO_MATRIX

!%      TODO comment
  SUBROUTINE MATRIX_TO_STATES(matrix, states)
    IMPLICIT NONE
    TYPE(STATESDT), INTENT(INOUT) :: states
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(states%hp, 1), SIZE(states%hp, 2), ns), &
&   INTENT(IN) :: matrix
    states%hi(:, :) = matrix(:, :, 1)
    states%hp(:, :) = matrix(:, :, 2)
    states%hft(:, :) = matrix(:, :, 3)
    states%hst(:, :) = matrix(:, :, 4)
    states%hlr(:, :) = matrix(:, :, 5)
  END SUBROUTINE MATRIX_TO_STATES

!%      TODO comment
  SUBROUTINE VECTOR_TO_STATES(vector, states)
    IMPLICIT NONE
    TYPE(STATESDT), INTENT(INOUT) :: states
    REAL(sp), DIMENSION(ns), INTENT(IN) :: vector
    states%hi = vector(1)
    states%hp = vector(2)
    states%hft = vector(3)
    states%hst = vector(4)
    states%hlr = vector(5)
  END SUBROUTINE VECTOR_TO_STATES

!%      TODO comment        
  SUBROUTINE SET0_STATES(states)
    IMPLICIT NONE
    TYPE(STATESDT), INTENT(INOUT) :: states
    REAL(sp), DIMENSION(ns) :: vector0
    vector0 = 0._sp
    CALL VECTOR_TO_STATES(vector0, states)
  END SUBROUTINE SET0_STATES

END MODULE MWD_STATES_DIFF_B

!%      This module `mwd_output` encapsulates all SMASH output.
!%      This module is wrapped and differentiated.
!%
!%      OutputDT type:
!%      
!%      </> Public
!%      ======================== =======================================
!%      `Variables`              Description
!%      ======================== =======================================
!%      ``qsim``                 Simulated discharge at gauge            [m3/s]
!%      ``qsim_domain``          Simulated discharge whole domain        [m3/s]
!%      ``sparse_qsim_domain``   Sparse simulated discharge whole domain [m3/s]
!%      ``parameters_gradient``  Parameters gradients
!%      ``cost``                 Cost value
!%      ``sp1``                  Scalar product <dY*, dY>
!%      ``sp2``                  Scalar product <dk*, dk>
!%      ``an``                   Alpha gradient test 
!%      ``ian``                  Ialpha gradient test
!%      ======================== =======================================
!%
!%      contains
!%
!%      [1] OutputDT_initialise
!%      [2] output_copy
MODULE MWD_OUTPUT_DIFF_B
!% only: sp, dp, lchar, np, ns
  USE MWD_COMMON
!% only: SetupDT
  USE MWD_SETUP
!%only: MeshDT
  USE MWD_MESH
!%only: StatesDT, StatesDT_initialise
  USE MWD_STATES_DIFF_B
  IMPLICIT NONE
  TYPE OUTPUTDT
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: qsim
      REAL(sp), DIMENSION(:, :, :), ALLOCATABLE :: qsim_domain
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: sparse_qsim_domain
      REAL(sp), DIMENSION(:, :, :), ALLOCATABLE :: parameters_gradient
      REAL(sp) :: cost
      REAL(sp) :: sp1
      REAL(sp) :: sp2
      REAL(sp), DIMENSION(:), ALLOCATABLE :: an
      REAL(sp), DIMENSION(:), ALLOCATABLE :: ian
      TYPE(STATESDT) :: fstates
  END TYPE OUTPUTDT
  TYPE OUTPUTDT_DIFF_B
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: qsim
  END TYPE OUTPUTDT_DIFF_B

CONTAINS
  SUBROUTINE OUTPUTDT_INITIALISE(output, setup, mesh)
    IMPLICIT NONE
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    TYPE(SETUPDT), INTENT(INOUT) :: setup
    TYPE(MESHDT), INTENT(INOUT) :: mesh
    ALLOCATE(output%qsim(mesh%ng, setup%ntime_step))
    output%qsim = -99._sp
    IF (setup%save_qsim_domain) THEN
      IF (setup%sparse_storage) THEN
        ALLOCATE(output%sparse_qsim_domain(mesh%nac, setup%ntime_step))
        output%sparse_qsim_domain = -99._sp
      ELSE
        ALLOCATE(output%qsim_domain(mesh%nrow, mesh%ncol, setup%&
&       ntime_step))
        output%qsim_domain = -99._sp
      END IF
    END IF
    CALL STATESDT_INITIALISE(output%fstates, mesh)
  END SUBROUTINE OUTPUTDT_INITIALISE

!%      TODO comment 
  SUBROUTINE OUTPUT_COPY(output_in, output_out)
    IMPLICIT NONE
    TYPE(OUTPUTDT), INTENT(IN) :: output_in
    TYPE(OUTPUTDT), INTENT(OUT) :: output_out
    output_out = output_in
  END SUBROUTINE OUTPUT_COPY

END MODULE MWD_OUTPUT_DIFF_B

!%    This module `mw_cost` encapsulates all SMASH cost (type, subroutines, functions)
!%
!%      contains
!%
!%      [1]  compute_jobs
!%      [2]  compute_jreg
!%      [3]  compute_cost
!%      [4]  nse
!%      [5]  kge_components
!%      [6]  kge
!%      [7]  se
!%      [8]  rmse
!%      [9]  logarithmique
!%      [10] reg_prior
MODULE MWD_COST_DIFF_B
!% only: sp, dp, lchar, np, ns
  USE MWD_COMMON
!% only: SetupDT
  USE MWD_SETUP
!%only: MeshDT
  USE MWD_MESH
!% only: Input_DataDT
  USE MWD_INPUT_DATA
!% only: ParametersDT, parameters_to_matrix
  USE MWD_PARAMETERS_DIFF_B
!% only: StatesDT, states_to_matrix
  USE MWD_STATES_DIFF_B
!% only: OutputDT
  USE MWD_OUTPUT_DIFF_B
  IMPLICIT NONE
  PUBLIC :: compute_jobs, compute_jreg, compute_cost
  PUBLIC :: compute_jobs_b, compute_jreg_b, compute_cost_b

CONTAINS
!  Differentiation of compute_jobs in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: jobs
!   with respect to varying inputs: *(output.qsim)
!   Plus diff mem management of: output.qsim:in
!% TODO comment
  SUBROUTINE COMPUTE_JOBS_B(setup, mesh, input_data, output, output_b, &
&   jobs, jobs_b)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(INPUT_DATADT), INTENT(IN) :: input_data
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    TYPE(OUTPUTDT_DIFF_B), INTENT(INOUT) :: output_b
    REAL(sp) :: jobs
    REAL(sp) :: jobs_b
    REAL(sp), DIMENSION(setup%ntime_step-setup%optim_start_step+1) :: qo&
&   , qs
    REAL(sp), DIMENSION(setup%ntime_step-setup%optim_start_step+1) :: &
&   qs_b
    REAL(sp), DIMENSION(mesh%ng) :: gauge_jobs
    REAL(sp), DIMENSION(mesh%ng) :: gauge_jobs_b
    REAL(sp) :: imd
    REAL(sp) :: imd_b
    INTEGER :: g, row, col
    INTRINSIC REAL
    INTRINSIC ANY
    INTEGER :: branch
    DO g=1,mesh%ng
      qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*setup&
&       %dt/mesh%area(g)*1e3_sp
      row = mesh%gauge_pos(1, g)
      col = mesh%gauge_pos(2, g)
      CALL PUSHREAL4ARRAY(qo, setup%ntime_step - setup%optim_start_step &
&                   + 1)
      qo = input_data%qobs(g, setup%optim_start_step:setup%ntime_step)*&
&       setup%dt/(REAL(mesh%drained_area(row, col))*mesh%dx*mesh%dx)*&
&       1e3_sp
      IF (ANY(qo .GE. 0._sp)) THEN
        SELECT CASE  (setup%jobs_fun) 
        CASE ('nse') 
          CALL PUSHCONTROL3B(6)
        CASE ('kge') 
          CALL PUSHCONTROL3B(5)
        CASE ('kge2') 
          CALL PUSHREAL4(imd)
          imd = KGE(qo, qs)
          CALL PUSHCONTROL3B(4)
        CASE ('se') 
          CALL PUSHCONTROL3B(3)
        CASE ('rmse') 
          CALL PUSHCONTROL3B(2)
        CASE ('logarithmique') 
          CALL PUSHCONTROL3B(1)
        CASE DEFAULT
          CALL PUSHCONTROL3B(7)
        END SELECT
      ELSE
        CALL PUSHCONTROL3B(0)
      END IF
    END DO
    gauge_jobs_b = 0.0_4
    DO g=mesh%ng,1,-1
      gauge_jobs_b(g) = gauge_jobs_b(g) + mesh%wgauge(g)*jobs_b
    END DO
    output_b%qsim = 0.0_4
    DO g=mesh%ng,1,-1
      CALL POPCONTROL3B(branch)
      IF (branch .LT. 4) THEN
        IF (branch .LT. 2) THEN
          IF (branch .EQ. 0) THEN
            qs_b = 0.0_4
          ELSE
            qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)&
&             *setup%dt/mesh%area(g)*1e3_sp
            CALL LOGARITHMIQUE_B(qo, qs, qs_b, gauge_jobs_b(g))
            gauge_jobs_b(g) = 0.0_4
          END IF
        ELSE IF (branch .EQ. 2) THEN
          qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*&
&           setup%dt/mesh%area(g)*1e3_sp
          CALL RMSE_B(qo, qs, qs_b, gauge_jobs_b(g))
          gauge_jobs_b(g) = 0.0_4
        ELSE
          qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*&
&           setup%dt/mesh%area(g)*1e3_sp
          CALL SE_B(qo, qs, qs_b, gauge_jobs_b(g))
          gauge_jobs_b(g) = 0.0_4
        END IF
      ELSE IF (branch .LT. 6) THEN
        IF (branch .EQ. 4) THEN
          imd_b = 2*imd*gauge_jobs_b(g)
          gauge_jobs_b(g) = 0.0_4
          qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*&
&           setup%dt/mesh%area(g)*1e3_sp
          CALL POPREAL4(imd)
          CALL KGE_B(qo, qs, qs_b, imd_b)
        ELSE
          qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*&
&           setup%dt/mesh%area(g)*1e3_sp
          CALL KGE_B(qo, qs, qs_b, gauge_jobs_b(g))
          gauge_jobs_b(g) = 0.0_4
        END IF
      ELSE IF (branch .EQ. 6) THEN
        qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*&
&         setup%dt/mesh%area(g)*1e3_sp
        CALL NSE_B(qo, qs, qs_b, gauge_jobs_b(g))
        gauge_jobs_b(g) = 0.0_4
      ELSE
        qs_b = 0.0_4
      END IF
      CALL POPREAL4ARRAY(qo, setup%ntime_step - setup%optim_start_step +&
&                  1)
      output_b%qsim(g, setup%optim_start_step:setup%ntime_step) = &
&       output_b%qsim(g, setup%optim_start_step:setup%ntime_step) + &
&       setup%dt*1e3_sp*qs_b/mesh%area(g)
    END DO
  END SUBROUTINE COMPUTE_JOBS_B

!% TODO comment
  SUBROUTINE COMPUTE_JOBS(setup, mesh, input_data, output, jobs)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(INPUT_DATADT), INTENT(IN) :: input_data
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    REAL(sp), INTENT(OUT) :: jobs
    REAL(sp), DIMENSION(setup%ntime_step-setup%optim_start_step+1) :: qo&
&   , qs
    REAL(sp), DIMENSION(mesh%ng) :: gauge_jobs
    REAL(sp) :: imd
    INTEGER :: g, row, col
    INTRINSIC REAL
    INTRINSIC ANY
    jobs = 0._sp
    gauge_jobs = 0._sp
    DO g=1,mesh%ng
      qs = output%qsim(g, setup%optim_start_step:setup%ntime_step)*setup&
&       %dt/mesh%area(g)*1e3_sp
      row = mesh%gauge_pos(1, g)
      col = mesh%gauge_pos(2, g)
      qo = input_data%qobs(g, setup%optim_start_step:setup%ntime_step)*&
&       setup%dt/(REAL(mesh%drained_area(row, col))*mesh%dx*mesh%dx)*&
&       1e3_sp
      IF (ANY(qo .GE. 0._sp)) THEN
        SELECT CASE  (setup%jobs_fun) 
        CASE ('nse') 
          gauge_jobs(g) = NSE(qo, qs)
        CASE ('kge') 
          gauge_jobs(g) = KGE(qo, qs)
        CASE ('kge2') 
          imd = KGE(qo, qs)
          gauge_jobs(g) = imd*imd
        CASE ('se') 
          gauge_jobs(g) = SE(qo, qs)
        CASE ('rmse') 
          gauge_jobs(g) = RMSE(qo, qs)
        CASE ('logarithmique') 
          gauge_jobs(g) = LOGARITHMIQUE(qo, qs)
        END SELECT
      END IF
    END DO
    DO g=1,mesh%ng
      jobs = jobs + mesh%wgauge(g)*gauge_jobs(g)
    END DO
  END SUBROUTINE COMPUTE_JOBS

!  Differentiation of compute_jreg in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: jreg
!   with respect to varying inputs: *(parameters.ci) *(parameters.cp)
!                *(parameters.beta) *(parameters.cft) *(parameters.cst)
!                *(parameters.alpha) *(parameters.exc) *(parameters.lr)
!                *(states.hi) *(states.hp) *(states.hft) *(states.hst)
!                *(states.hlr)
!   Plus diff mem management of: parameters.ci:in parameters.cp:in
!                parameters.beta:in parameters.cft:in parameters.cst:in
!                parameters.alpha:in parameters.exc:in parameters.lr:in
!                states.hi:in states.hp:in states.hft:in states.hst:in
!                states.hlr:in
!% TODO comment
  SUBROUTINE COMPUTE_JREG_B(setup, mesh, parameters, parameters_b, &
&   parameters_bgd, states, states_b, states_bgd, jreg, jreg_b)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters, parameters_bgd
    TYPE(PARAMETERSDT) :: parameters_b
    TYPE(STATESDT), INTENT(IN) :: states, states_bgd
    TYPE(STATESDT) :: states_b
    REAL(sp), INTENT(INOUT) :: jreg
    REAL(sp), INTENT(INOUT) :: jreg_b
    REAL(sp) :: parameters_jreg, states_jreg
    REAL(sp) :: parameters_jreg_b, states_jreg_b
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, np) :: parameters_matrix, &
&   parameters_bgd_matrix
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, np) :: parameters_matrix_b
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, ns) :: states_matrix, &
&   states_bgd_matrix
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, ns) :: states_matrix_b
    INTEGER :: branch
    CALL PARAMETERS_TO_MATRIX(parameters, parameters_matrix)
    CALL PARAMETERS_TO_MATRIX(parameters_bgd, parameters_bgd_matrix)
    CALL STATES_TO_MATRIX(states, states_matrix)
    CALL STATES_TO_MATRIX(states_bgd, states_bgd_matrix)
    SELECT CASE  (setup%jreg_fun) 
    CASE ('prior') 
      CALL PUSHCONTROL1B(1)
    CASE DEFAULT
      CALL PUSHCONTROL1B(0)
    END SELECT
    parameters_jreg_b = jreg_b
    states_jreg_b = jreg_b
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      states_matrix_b = 0.0_4
      parameters_matrix_b = 0.0_4
    ELSE
      CALL REG_PRIOR_B(mesh, ns, states_matrix, states_matrix_b, &
&                states_bgd_matrix, states_jreg_b)
      CALL REG_PRIOR_B(mesh, np, parameters_matrix, parameters_matrix_b&
&                , parameters_bgd_matrix, parameters_jreg_b)
    END IF
    CALL STATES_TO_MATRIX_B(states, states_b, states_matrix, &
&                     states_matrix_b)
    CALL PARAMETERS_TO_MATRIX_B(parameters, parameters_b, &
&                         parameters_matrix, parameters_matrix_b)
  END SUBROUTINE COMPUTE_JREG_B

!% TODO comment
  SUBROUTINE COMPUTE_JREG(setup, mesh, parameters, parameters_bgd, &
&   states, states_bgd, jreg)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters, parameters_bgd
    TYPE(STATESDT), INTENT(IN) :: states, states_bgd
    REAL(sp), INTENT(INOUT) :: jreg
    REAL(sp) :: parameters_jreg, states_jreg
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, np) :: parameters_matrix, &
&   parameters_bgd_matrix
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, ns) :: states_matrix, &
&   states_bgd_matrix
    CALL PARAMETERS_TO_MATRIX(parameters, parameters_matrix)
    CALL PARAMETERS_TO_MATRIX(parameters_bgd, parameters_bgd_matrix)
    CALL STATES_TO_MATRIX(states, states_matrix)
    CALL STATES_TO_MATRIX(states_bgd, states_bgd_matrix)
    jreg = 0._sp
    parameters_jreg = 0._sp
    states_jreg = 0._sp
    SELECT CASE  (setup%jreg_fun) 
    CASE ('prior') 
!% Normalize prior between parameters and states
      parameters_jreg = REG_PRIOR(mesh, np, parameters_matrix, &
&       parameters_bgd_matrix)
      states_jreg = REG_PRIOR(mesh, ns, states_matrix, states_bgd_matrix&
&       )
    END SELECT
    jreg = parameters_jreg + states_jreg
  END SUBROUTINE COMPUTE_JREG

!  Differentiation of compute_cost in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: cost
!   with respect to varying inputs: *(parameters.ci) *(parameters.cp)
!                *(parameters.beta) *(parameters.cft) *(parameters.cst)
!                *(parameters.alpha) *(parameters.exc) *(parameters.lr)
!                *(output.qsim) *(states.hi) *(states.hp) *(states.hft)
!                *(states.hst) *(states.hlr)
!   Plus diff mem management of: parameters.ci:in parameters.cp:in
!                parameters.beta:in parameters.cft:in parameters.cst:in
!                parameters.alpha:in parameters.exc:in parameters.lr:in
!                output.qsim:in states.hi:in states.hp:in states.hft:in
!                states.hst:in states.hlr:in
!% TODO comment
  SUBROUTINE COMPUTE_COST_B(setup, mesh, input_data, parameters, &
&   parameters_b, parameters_bgd, states, states_b, states_bgd, output, &
&   output_b, cost, cost_b)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(INPUT_DATADT), INTENT(IN) :: input_data
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters, parameters_bgd
    TYPE(PARAMETERSDT) :: parameters_b
    TYPE(STATESDT), INTENT(IN) :: states, states_bgd
    TYPE(STATESDT) :: states_b
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    TYPE(OUTPUTDT_DIFF_B), INTENT(INOUT) :: output_b
    REAL(sp), INTENT(INOUT) :: cost
    REAL(sp), INTENT(INOUT) :: cost_b
    REAL(sp) :: jobs, jreg
    REAL(sp) :: jobs_b, jreg_b
    INTEGER :: branch
!% Only compute in case wjreg > 0
    IF (setup%wjreg .GT. 0._sp) THEN
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    jobs_b = cost_b
    jreg_b = setup%wjreg*cost_b
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      CALL COMPUTE_JREG_B(setup, mesh, parameters, parameters_b, &
&                   parameters_bgd, states, states_b, states_bgd, jreg, &
&                   jreg_b)
    ELSE
      parameters_b%ci = 0.0_4
      parameters_b%cp = 0.0_4
      parameters_b%beta = 0.0_4
      parameters_b%cft = 0.0_4
      parameters_b%cst = 0.0_4
      parameters_b%alpha = 0.0_4
      parameters_b%exc = 0.0_4
      parameters_b%lr = 0.0_4
      states_b%hi = 0.0_4
      states_b%hp = 0.0_4
      states_b%hft = 0.0_4
      states_b%hst = 0.0_4
      states_b%hlr = 0.0_4
    END IF
    CALL COMPUTE_JOBS_B(setup, mesh, input_data, output, output_b, jobs&
&                 , jobs_b)
  END SUBROUTINE COMPUTE_COST_B

!% TODO comment
  SUBROUTINE COMPUTE_COST(setup, mesh, input_data, parameters, &
&   parameters_bgd, states, states_bgd, output, cost)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(INPUT_DATADT), INTENT(IN) :: input_data
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters, parameters_bgd
    TYPE(STATESDT), INTENT(IN) :: states, states_bgd
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    REAL(sp), INTENT(INOUT) :: cost
    REAL(sp) :: jobs, jreg
    CALL COMPUTE_JOBS(setup, mesh, input_data, output, jobs)
!% Only compute in case wjreg > 0
    IF (setup%wjreg .GT. 0._sp) THEN
      CALL COMPUTE_JREG(setup, mesh, parameters, parameters_bgd, states&
&                 , states_bgd, jreg)
    ELSE
      jreg = 0._sp
    END IF
    cost = jobs + setup%wjreg*jreg
    output%cost = cost
  END SUBROUTINE COMPUTE_COST

!  Differentiation of nse in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: res
!   with respect to varying inputs: y
!% TODO comment
  SUBROUTINE NSE_B(x, y, y_b, res_b)
    IMPLICIT NONE
    REAL(sp), DIMENSION(:), INTENT(IN) :: x, y
    REAL(sp), DIMENSION(:) :: y_b
    REAL(sp) :: res
    REAL(sp) :: res_b
    REAL(sp) :: sum_x, sum_xx, sum_yy, sum_xy, mean_x, num, den
    REAL(sp) :: sum_yy_b, sum_xy_b, num_b
    INTEGER :: i, n
    INTRINSIC SIZE
    INTEGER :: ad_to
    INTEGER :: branch
!% Metric computation
    n = 0
    sum_x = 0.
    sum_xx = 0.
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) THEN
        n = n + 1
        sum_x = sum_x + x(i)
        sum_xx = sum_xx + x(i)*x(i)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    CALL PUSHINTEGER4(i - 1)
    mean_x = sum_x/n
!% NSE numerator / denominator
    den = sum_xx - n*mean_x*mean_x
!% NSE criterion
    num_b = res_b/den
    sum_yy_b = num_b
    sum_xy_b = -(2*num_b)
    y_b = 0.0_4
    CALL POPINTEGER4(ad_to)
    DO i=ad_to,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) y_b(i) = y_b(i) + x(i)*sum_xy_b + 2*y(i)*&
&         sum_yy_b
    END DO
  END SUBROUTINE NSE_B

!% TODO comment
  FUNCTION NSE(x, y) RESULT (RES)
    IMPLICIT NONE
    REAL(sp), DIMENSION(:), INTENT(IN) :: x, y
    REAL(sp) :: res
    REAL(sp) :: sum_x, sum_xx, sum_yy, sum_xy, mean_x, num, den
    INTEGER :: i, n
    INTRINSIC SIZE
!% Metric computation
    n = 0
    sum_x = 0.
    sum_xx = 0.
    sum_yy = 0.
    sum_xy = 0.
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) THEN
        n = n + 1
        sum_x = sum_x + x(i)
        sum_xx = sum_xx + x(i)*x(i)
        sum_yy = sum_yy + y(i)*y(i)
        sum_xy = sum_xy + x(i)*y(i)
      END IF
    END DO
    mean_x = sum_x/n
!% NSE numerator / denominator
    num = sum_xx - 2*sum_xy + sum_yy
    den = sum_xx - n*mean_x*mean_x
!% NSE criterion
    res = num/den
  END FUNCTION NSE

!  Differentiation of kge_components in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: r a b
!   with respect to varying inputs: y
!% TODO comment
  SUBROUTINE KGE_COMPONENTS_B(x, y, y_b, r, r_b, a, a_b, b, b_b)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL, DIMENSION(:) :: y_b
    REAL, INTENT(INOUT) :: r, a, b
    REAL, INTENT(INOUT) :: r_b, a_b, b_b
    REAL :: sum_x, sum_y, sum_xx, sum_yy, sum_xy, mean_x, mean_y, var_x&
&   , var_y, cov
    REAL :: sum_y_b, sum_yy_b, sum_xy_b, mean_y_b, var_y_b, cov_b
    INTEGER :: n, i
    INTRINSIC SIZE
    INTRINSIC SQRT
    REAL :: temp
    REAL :: temp0
    REAL :: temp1
    INTEGER :: ad_to
    INTEGER :: branch
! Metric computation
    n = 0
    sum_x = 0.
    sum_y = 0.
    sum_xx = 0.
    sum_yy = 0.
    sum_xy = 0.
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) THEN
        n = n + 1
        sum_x = sum_x + x(i)
        sum_y = sum_y + y(i)
        sum_xx = sum_xx + x(i)*x(i)
        sum_yy = sum_yy + y(i)*y(i)
        sum_xy = sum_xy + x(i)*y(i)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    CALL PUSHINTEGER4(i - 1)
    mean_x = sum_x/n
    mean_y = sum_y/n
    var_x = sum_xx/n - mean_x*mean_x
    var_y = sum_yy/n - mean_y*mean_y
    cov = sum_xy/n - mean_x*mean_y
! KGE components (r, alpha, beta)
    IF (var_y .EQ. 0.0) THEN
      var_y_b = 0.0
    ELSE
      var_y_b = a_b/(2.0*SQRT(var_y)*SQRT(var_x))
    END IF
    temp = SQRT(var_y)
    temp0 = SQRT(var_x)
    temp1 = temp0*temp
    cov_b = r_b/temp1
    IF (.NOT.var_y .EQ. 0.0) var_y_b = var_y_b - temp0*cov*r_b/(2.0*temp&
&       *temp1**2)
    mean_y_b = b_b/mean_x - mean_x*cov_b - 2*mean_y*var_y_b
    sum_xy_b = cov_b/n
    sum_yy_b = var_y_b/n
    sum_y_b = mean_y_b/n
    y_b = 0.0
    CALL POPINTEGER4(ad_to)
    DO i=ad_to,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) y_b(i) = y_b(i) + x(i)*sum_xy_b + 2*y(i)*&
&         sum_yy_b + sum_y_b
    END DO
  END SUBROUTINE KGE_COMPONENTS_B

!% TODO comment
  SUBROUTINE KGE_COMPONENTS(x, y, r, a, b)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL, INTENT(INOUT) :: r, a, b
    REAL :: sum_x, sum_y, sum_xx, sum_yy, sum_xy, mean_x, mean_y, var_x&
&   , var_y, cov
    INTEGER :: n, i
    INTRINSIC SIZE
    INTRINSIC SQRT
! Metric computation
    n = 0
    sum_x = 0.
    sum_y = 0.
    sum_xx = 0.
    sum_yy = 0.
    sum_xy = 0.
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) THEN
        n = n + 1
        sum_x = sum_x + x(i)
        sum_y = sum_y + y(i)
        sum_xx = sum_xx + x(i)*x(i)
        sum_yy = sum_yy + y(i)*y(i)
        sum_xy = sum_xy + x(i)*y(i)
      END IF
    END DO
    mean_x = sum_x/n
    mean_y = sum_y/n
    var_x = sum_xx/n - mean_x*mean_x
    var_y = sum_yy/n - mean_y*mean_y
    cov = sum_xy/n - mean_x*mean_y
! KGE components (r, alpha, beta)
    r = cov/SQRT(var_x)/SQRT(var_y)
    a = SQRT(var_y)/SQRT(var_x)
    b = mean_y/mean_x
  END SUBROUTINE KGE_COMPONENTS

!  Differentiation of kge in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: res
!   with respect to varying inputs: y
!% TODO comment
  SUBROUTINE KGE_B(x, y, y_b, res_b)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL, DIMENSION(:) :: y_b
    REAL :: res
    REAL :: res_b
    REAL :: r, a, b
    REAL :: r_b, a_b, b_b
    INTRINSIC SQRT
    REAL :: temp_b
    CALL KGE_COMPONENTS(x, y, r, a, b)
! KGE criterion
    IF ((r-1)**2 + (b-1)**2 + (a-1)**2 .EQ. 0.0) THEN
      temp_b = 0.0
    ELSE
      temp_b = res_b/(2.0*SQRT((r-1)**2+(b-1)**2+(a-1)**2))
    END IF
    r_b = 2*(r-1)*temp_b
    b_b = 2*(b-1)*temp_b
    a_b = 2*(a-1)*temp_b
    CALL KGE_COMPONENTS_B(x, y, y_b, r, r_b, a, a_b, b, b_b)
  END SUBROUTINE KGE_B

!% TODO comment
  FUNCTION KGE(x, y) RESULT (RES)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL :: res
    REAL :: r, a, b
    INTRINSIC SQRT
    CALL KGE_COMPONENTS(x, y, r, a, b)
! KGE criterion
    res = SQRT((r-1)*(r-1) + (b-1)*(b-1) + (a-1)*(a-1))
  END FUNCTION KGE

!  Differentiation of se in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: res
!   with respect to varying inputs: y
!% TODO comment
  SUBROUTINE SE_B(x, y, y_b, res_b)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL, DIMENSION(:) :: y_b
    REAL :: res
    REAL :: res_b
    INTEGER :: i
    INTRINSIC SIZE
    INTEGER :: ad_to
    INTEGER :: branch
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) THEN
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    ad_to = i - 1
    y_b = 0.0
    DO i=ad_to,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) y_b(i) = y_b(i) - 2*(x(i)-y(i))*res_b
    END DO
  END SUBROUTINE SE_B

!% TODO comment
  FUNCTION SE(x, y) RESULT (RES)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL :: res
    INTEGER :: i
    INTRINSIC SIZE
    res = 0.
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) res = res + (x(i)-y(i))*(x(i)-y(i))
    END DO
  END FUNCTION SE

!  Differentiation of rmse in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: res
!   with respect to varying inputs: y
!% TODO comment
  SUBROUTINE RMSE_B(x, y, y_b, res_b)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL, DIMENSION(:) :: y_b
    REAL :: res
    REAL :: res_b
    INTEGER :: i, n
    INTRINSIC SIZE
    INTRINSIC SQRT
    REAL :: result1
    REAL :: result1_b
    INTEGER :: ad_to
    INTEGER :: branch
    n = 0
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) THEN
        CALL PUSHCONTROL1B(1)
        n = n + 1
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    CALL PUSHINTEGER4(i - 1)
    result1 = SE(x, y)
    IF (result1/n .EQ. 0.0) THEN
      result1_b = 0.0
    ELSE
      result1_b = res_b/(n*2.0*SQRT(result1/n))
    END IF
    CALL SE_B(x, y, y_b, result1_b)
    CALL POPINTEGER4(ad_to)
    DO i=ad_to,1,-1
      CALL POPCONTROL1B(branch)
    END DO
  END SUBROUTINE RMSE_B

!% TODO comment
  FUNCTION RMSE(x, y) RESULT (RES)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL :: res
    INTEGER :: i, n
    INTRINSIC SIZE
    INTRINSIC SQRT
    REAL :: result1
    n = 0
    DO i=1,SIZE(x)
      IF (x(i) .GE. 0.) n = n + 1
    END DO
    result1 = SE(x, y)
    res = SQRT(result1/n)
  END FUNCTION RMSE

!  Differentiation of logarithmique in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: res
!   with respect to varying inputs: y
!% TODO comment
  SUBROUTINE LOGARITHMIQUE_B(x, y, y_b, res_b)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL, DIMENSION(:) :: y_b
    REAL :: res
    REAL :: res_b
    INTEGER :: i
    INTRINSIC SIZE
    INTRINSIC LOG
    REAL :: temp
    INTEGER :: ad_to
    INTEGER :: branch
    DO i=1,SIZE(x)
      IF (x(i) .GT. 0. .AND. y(i) .GT. 0.) THEN
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    ad_to = i - 1
    y_b = 0.0
    DO i=ad_to,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        temp = y(i)/x(i)
        y_b(i) = y_b(i) + 2*LOG(temp)*res_b/temp
      END IF
    END DO
  END SUBROUTINE LOGARITHMIQUE_B

!% TODO comment
  FUNCTION LOGARITHMIQUE(x, y) RESULT (RES)
    IMPLICIT NONE
    REAL, DIMENSION(:), INTENT(IN) :: x, y
    REAL :: res
    INTEGER :: i
    INTRINSIC SIZE
    INTRINSIC LOG
    res = 0.
    DO i=1,SIZE(x)
      IF (x(i) .GT. 0. .AND. y(i) .GT. 0.) res = res + x(i)*LOG(y(i)/x(i&
&         ))*LOG(y(i)/x(i))
    END DO
  END FUNCTION LOGARITHMIQUE

!  Differentiation of reg_prior in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: res
!   with respect to varying inputs: matrix
!% TODO comment
  SUBROUTINE REG_PRIOR_B(mesh, size_mat3, matrix, matrix_b, matrix_bgd, &
&   res_b)
    IMPLICIT NONE
    TYPE(MESHDT), INTENT(IN) :: mesh
    INTEGER, INTENT(IN) :: size_mat3
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, size_mat3), INTENT(IN) :: &
&   matrix, matrix_bgd
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, size_mat3) :: matrix_b
    REAL(sp) :: res
    REAL(sp) :: res_b
    INTRINSIC SUM
    matrix_b = 0.0_4
    matrix_b = 2*(matrix-matrix_bgd)*res_b
  END SUBROUTINE REG_PRIOR_B

!% TODO comment
  FUNCTION REG_PRIOR(mesh, size_mat3, matrix, matrix_bgd) RESULT (RES)
    IMPLICIT NONE
    TYPE(MESHDT), INTENT(IN) :: mesh
    INTEGER, INTENT(IN) :: size_mat3
    REAL(sp), DIMENSION(mesh%nrow, mesh%ncol, size_mat3), INTENT(IN) :: &
&   matrix, matrix_bgd
    REAL(sp) :: res
    INTRINSIC SUM
    res = SUM((matrix-matrix_bgd)*(matrix-matrix_bgd))
  END FUNCTION REG_PRIOR

END MODULE MWD_COST_DIFF_B

!%      This module `md_operator` encapsulates all SMASH operator.
!%      This module is differentiated.
!%
!%      contains
!%
!%      [1] GR_interception
!%      [2] GR_production
!%      [3] GR_exchange
!%      [4] GR_transferN
!%      [5] upstream_discharge
!%      [6] sparse_upstream_discharge
!%      [7] GR_transfer1
MODULE MD_OPERATOR_DIFF_B
!% only : sp
  USE MWD_COMMON
  IMPLICIT NONE

CONTAINS
!  Differentiation of gr_interception in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: hi ei ci pn
!   with respect to varying inputs: hi ci
!% TODO Renommer argument pour etre global
  SUBROUTINE GR_INTERCEPTION_B(prcp, pet, ci, ci_b, hi, hi_b, pn, pn_b, &
&   ei, ei_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: prcp, pet, ci
    REAL(sp) :: ci_b
    REAL(sp), INTENT(INOUT) :: hi
    REAL(sp), INTENT(INOUT) :: hi_b
    REAL(sp) :: pn, ei
    REAL(sp) :: pn_b, ei_b
    INTRINSIC MIN
    INTRINSIC MAX
    REAL(sp) :: temp_b
    INTEGER :: branch
    IF (pet .GT. prcp + hi*ci) THEN
      ei = prcp + hi*ci
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
      ei = pet
    END IF
    IF (0._sp .LT. prcp - ci*(1._sp-hi) - ei) THEN
      pn = prcp - ci*(1._sp-hi) - ei
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
      pn = 0._sp
    END IF
    temp_b = hi_b/ci
    ei_b = ei_b - temp_b
    pn_b = pn_b - temp_b
    ci_b = ci_b - (prcp-ei-pn)*temp_b/ci
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      ci_b = ci_b - (1._sp-hi)*pn_b
      hi_b = hi_b + ci*pn_b
      ei_b = ei_b - pn_b
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      hi_b = hi_b + ci*ei_b
      ci_b = ci_b + hi*ei_b
    END IF
  END SUBROUTINE GR_INTERCEPTION_B

!% TODO Renommer argument pour etre global
  SUBROUTINE GR_INTERCEPTION(prcp, pet, ci, hi, pn, ei)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: prcp, pet, ci
    REAL(sp), INTENT(INOUT) :: hi
    REAL(sp), INTENT(OUT) :: pn, ei
    INTRINSIC MIN
    INTRINSIC MAX
    IF (pet .GT. prcp + hi*ci) THEN
      ei = prcp + hi*ci
    ELSE
      ei = pet
    END IF
    IF (0._sp .LT. prcp - ci*(1._sp-hi) - ei) THEN
      pn = prcp - ci*(1._sp-hi) - ei
    ELSE
      pn = 0._sp
    END IF
    hi = hi + (prcp-ei-pn)/ci
  END SUBROUTINE GR_INTERCEPTION

!  Differentiation of gr_production in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: hp beta cp perc pr
!   with respect to varying inputs: hp en beta cp pn
  SUBROUTINE GR_PRODUCTION_B(pn, pn_b, en, en_b, cp, cp_b, beta, beta_b&
&   , hp, hp_b, pr, pr_b, perc, perc_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: pn, en, cp, beta
    REAL(sp) :: pn_b, en_b, cp_b, beta_b
    REAL(sp), INTENT(INOUT) :: hp
    REAL(sp), INTENT(INOUT) :: hp_b
    REAL(sp) :: pr, perc
    REAL(sp) :: pr_b, perc_b
    REAL(sp) :: inv_cp, ps, es, hp_imd
    REAL(sp) :: inv_cp_b, ps_b, es_b, hp_imd_b
    INTRINSIC TANH
    REAL(sp) :: temp
    REAL(sp) :: temp0
    REAL(sp) :: temp_b
    REAL(sp) :: temp1
    REAL(sp) :: temp2
    REAL(sp) :: temp3
    REAL(sp) :: temp_b0
    REAL(sp) :: temp_b1
    REAL(sp) :: temp4
    REAL(sp) :: temp_b2
    REAL(sp) :: temp_b3
    REAL(sp) :: temp_b4
    REAL(sp) :: temp5
    REAL(sp) :: temp_b5
    INTEGER :: branch
    inv_cp = 1._sp/cp
    ps = cp*(1._sp-hp*hp)*TANH(pn*inv_cp)/(1._sp+hp*TANH(pn*inv_cp))
    es = hp*cp*(2._sp-hp)*TANH(en*inv_cp)/(1._sp+(1._sp-hp)*TANH(en*&
&     inv_cp))
    hp_imd = hp + (ps-es)*inv_cp
    IF (pn .GT. 0) THEN
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    perc = hp_imd*cp*(1._sp-(1._sp+(hp_imd/beta)**4)**(-0.25_sp))
    perc_b = perc_b - inv_cp*hp_b
    temp5 = hp_imd/beta
    temp4 = temp5**4 + 1._sp
    temp_b0 = (1._sp-temp4**(-0.25_sp))*perc_b
    temp_b5 = 4*temp5**3*0.25_sp*temp4**(-1.25)*hp_imd*cp*perc_b/beta
    hp_imd_b = hp_b + temp_b5 + cp*temp_b0
    inv_cp_b = -(perc*hp_b)
    beta_b = beta_b - temp5*temp_b5
    cp_b = cp_b + hp_imd*temp_b0
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      pn_b = pr_b
      hp_imd_b = hp_imd_b - cp*pr_b
      hp_b = cp*pr_b
      cp_b = cp_b - (hp_imd-hp)*pr_b
    ELSE
      hp_b = 0.0_4
      pn_b = 0.0_4
    END IF
    es_b = -(inv_cp*hp_imd_b)
    temp4 = TANH(en*inv_cp)
    temp3 = (-hp+1._sp)*temp4 + 1._sp
    temp1 = TANH(en*inv_cp)
    temp0 = hp*cp*(-hp+2._sp)
    temp_b3 = es_b/temp3
    temp_b = (2._sp-hp)*temp1*temp_b3
    temp_b0 = -(temp0*temp1*temp_b3/temp3)
    hp_b = hp_b + hp_imd_b + cp*temp_b - hp*cp*temp1*temp_b3 - temp4*&
&     temp_b0
    ps_b = inv_cp*hp_imd_b
    temp_b4 = (1.0-TANH(en*inv_cp)**2)*temp0*temp_b3
    temp_b5 = (1.0-TANH(en*inv_cp)**2)*(1._sp-hp)*temp_b0
    en_b = inv_cp*temp_b5 + inv_cp*temp_b4
    cp_b = cp_b + hp*temp_b
    temp = TANH(pn*inv_cp)
    temp0 = hp*temp + 1._sp
    temp1 = TANH(pn*inv_cp)
    temp2 = cp*(-(hp*hp)+1._sp)
    temp_b = ps_b/temp0
    temp_b0 = (1.0-TANH(pn*inv_cp)**2)*temp2*temp_b
    temp_b1 = -(temp2*temp1*temp_b/temp0)
    hp_b = hp_b + temp*temp_b1 - 2*hp*cp*temp1*temp_b
    temp_b2 = (1.0-TANH(pn*inv_cp)**2)*hp*temp_b1
    inv_cp_b = inv_cp_b + (ps-es)*hp_imd_b + en*temp_b5 + en*temp_b4 + &
&     pn*temp_b2 + pn*temp_b0
    cp_b = cp_b + (1._sp-hp**2)*temp1*temp_b - inv_cp_b/cp**2
    pn_b = pn_b + inv_cp*temp_b2 + inv_cp*temp_b0
  END SUBROUTINE GR_PRODUCTION_B

  SUBROUTINE GR_PRODUCTION(pn, en, cp, beta, hp, pr, perc)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: pn, en, cp, beta
    REAL(sp), INTENT(INOUT) :: hp
    REAL(sp), INTENT(OUT) :: pr, perc
    REAL(sp) :: inv_cp, ps, es, hp_imd
    INTRINSIC TANH
    inv_cp = 1._sp/cp
    pr = 0._sp
    ps = cp*(1._sp-hp*hp)*TANH(pn*inv_cp)/(1._sp+hp*TANH(pn*inv_cp))
    es = hp*cp*(2._sp-hp)*TANH(en*inv_cp)/(1._sp+(1._sp-hp)*TANH(en*&
&     inv_cp))
    hp_imd = hp + (ps-es)*inv_cp
    IF (pn .GT. 0) pr = pn - (hp_imd-hp)*cp
    perc = hp_imd*cp*(1._sp-(1._sp+(hp_imd/beta)**4)**(-0.25_sp))
    hp = hp_imd - perc*inv_cp
  END SUBROUTINE GR_PRODUCTION

!  Differentiation of gr_exchange in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: l hft exc
!   with respect to varying inputs: hft exc
  SUBROUTINE GR_EXCHANGE_B(exc, exc_b, hft, hft_b, l, l_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: exc
    REAL(sp) :: exc_b
    REAL(sp), INTENT(INOUT) :: hft
    REAL(sp), INTENT(INOUT) :: hft_b
    REAL(sp) :: l
    REAL(sp) :: l_b
    exc_b = exc_b + hft**3.5_sp*l_b
    hft_b = hft_b + 3.5_sp*hft**2.5*exc*l_b
  END SUBROUTINE GR_EXCHANGE_B

  SUBROUTINE GR_EXCHANGE(exc, hft, l)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: exc
    REAL(sp), INTENT(INOUT) :: hft
    REAL(sp), INTENT(OUT) :: l
    l = exc*hft**3.5_sp
  END SUBROUTINE GR_EXCHANGE

!  Differentiation of gr_transfern in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: q ht ct
!   with respect to varying inputs: ht ct pr
  SUBROUTINE GR_TRANSFERN_B(n, prcp, pr, pr_b, ct, ct_b, ht, ht_b, q, &
&   q_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: n, prcp, pr, ct
    REAL(sp) :: pr_b, ct_b
    REAL(sp), INTENT(INOUT) :: ht
    REAL(sp), INTENT(INOUT) :: ht_b
    REAL(sp) :: q
    REAL(sp) :: q_b
    REAL(sp) :: pr_imd, ht_imd, nm1, d1pnm1
    REAL(sp) :: pr_imd_b, ht_imd_b
    INTRINSIC MAX
    REAL(sp) :: temp_b
    REAL(sp) :: temp
    REAL(sp) :: temp_b0
    INTEGER :: branch
    nm1 = n - 1._sp
    d1pnm1 = 1._sp/nm1
    IF (prcp .LT. 0._sp) THEN
      pr_imd = ((ht*ct)**(-nm1)-ct**(-nm1))**(-d1pnm1) - ht*ct
      CALL PUSHCONTROL1B(1)
    ELSE
      pr_imd = pr
      CALL PUSHCONTROL1B(0)
    END IF
    IF (1.e-6_sp .LT. ht + pr_imd/ct) THEN
      ht_imd = ht + pr_imd/ct
      CALL PUSHCONTROL1B(0)
    ELSE
      ht_imd = 1.e-6_sp
      CALL PUSHCONTROL1B(1)
    END IF
    CALL PUSHREAL4(ht)
    ht = ((ht_imd*ct)**(-nm1)+ct**(-nm1))**(-d1pnm1)/ct
    ht_b = ht_b - ct*q_b
    temp = (ht_imd*ct)**(-nm1) + ct**(-nm1)
    IF (temp .LE. 0.0 .AND. (-d1pnm1 .EQ. 0.0 .OR. -d1pnm1 .NE. INT(-&
&       d1pnm1))) THEN
      temp_b0 = 0.0_4
    ELSE
      temp_b0 = -(d1pnm1*temp**((-1)-d1pnm1)*ht_b/ct)
    END IF
    IF (ht_imd*ct .LE. 0.0 .AND. (-nm1 .EQ. 0.0 .OR. -nm1 .NE. INT(-nm1)&
&       )) THEN
      temp_b = 0.0_4
    ELSE
      temp_b = -(nm1*(ht_imd*ct)**((-1)-nm1)*temp_b0)
    END IF
    ht_imd_b = ct*q_b + ct*temp_b
    IF (ct .LE. 0.0 .AND. (-nm1 .EQ. 0.0 .OR. -nm1 .NE. INT(-nm1))) THEN
      ct_b = ct_b + (ht_imd-ht)*q_b + ht_imd*temp_b - temp**(-d1pnm1)*&
&       ht_b/ct**2
    ELSE
      ct_b = ct_b + (ht_imd-ht)*q_b + ht_imd*temp_b - temp**(-d1pnm1)*&
&       ht_b/ct**2 - nm1*ct**((-1)-nm1)*temp_b0
    END IF
    CALL POPREAL4(ht)
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      ht_b = ht_imd_b
      pr_imd_b = ht_imd_b/ct
      ct_b = ct_b - pr_imd*ht_imd_b/ct**2
    ELSE
      ht_b = 0.0_4
      pr_imd_b = 0.0_4
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      pr_b = pr_imd_b
    ELSE
      IF ((ht*ct)**(-nm1) - ct**(-nm1) .LE. 0.0 .AND. (-d1pnm1 .EQ. 0.0 &
&         .OR. -d1pnm1 .NE. INT(-d1pnm1))) THEN
        temp_b = 0.0_4
      ELSE
        temp_b = -(d1pnm1*((ht*ct)**(-nm1)-ct**(-nm1))**((-1)-d1pnm1)*&
&         pr_imd_b)
      END IF
      IF (ht*ct .LE. 0.0 .AND. (-nm1 .EQ. 0.0 .OR. -nm1 .NE. INT(-nm1))&
&     ) THEN
        temp_b0 = 0.0_4
      ELSE
        temp_b0 = -(nm1*(ht*ct)**((-1)-nm1)*temp_b)
      END IF
      ht_b = ht_b + ct*temp_b0 - ct*pr_imd_b
      IF (ct .LE. 0.0 .AND. (-nm1 .EQ. 0.0 .OR. -nm1 .NE. INT(-nm1))) &
&     THEN
        ct_b = ct_b + ht*temp_b0 - ht*pr_imd_b
      ELSE
        ct_b = ct_b + nm1*ct**((-1)-nm1)*temp_b - ht*pr_imd_b + ht*&
&         temp_b0
      END IF
      pr_b = 0.0_4
    END IF
  END SUBROUTINE GR_TRANSFERN_B

  SUBROUTINE GR_TRANSFERN(n, prcp, pr, ct, ht, q)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: n, prcp, pr, ct
    REAL(sp), INTENT(INOUT) :: ht
    REAL(sp), INTENT(OUT) :: q
    REAL(sp) :: pr_imd, ht_imd, nm1, d1pnm1
    INTRINSIC MAX
    nm1 = n - 1._sp
    d1pnm1 = 1._sp/nm1
    IF (prcp .LT. 0._sp) THEN
      pr_imd = ((ht*ct)**(-nm1)-ct**(-nm1))**(-d1pnm1) - ht*ct
    ELSE
      pr_imd = pr
    END IF
    IF (1.e-6_sp .LT. ht + pr_imd/ct) THEN
      ht_imd = ht + pr_imd/ct
    ELSE
      ht_imd = 1.e-6_sp
    END IF
    ht = ((ht_imd*ct)**(-nm1)+ct**(-nm1))**(-d1pnm1)/ct
    q = (ht_imd-ht)*ct
  END SUBROUTINE GR_TRANSFERN

!  Differentiation of upstream_discharge in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: q qup
!   with respect to varying inputs: q
  SUBROUTINE UPSTREAM_DISCHARGE_B(dt, dx, nrow, ncol, flow, drained_area&
&   , row, col, q, q_b, qup, qup_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: dt, dx
    INTEGER, INTENT(IN) :: nrow, ncol, row, col
    INTEGER, DIMENSION(nrow, ncol), INTENT(IN) :: flow, drained_area
    REAL(sp), DIMENSION(nrow, ncol), INTENT(IN) :: q
    REAL(sp), DIMENSION(nrow, ncol) :: q_b
    REAL(sp) :: qup
    REAL(sp) :: qup_b
    INTEGER :: i, row_imd, col_imd
    INTEGER, DIMENSION(8), SAVE :: dcol=(/0, -1, -1, -1, 0, 1, 1, 1/)
    INTEGER, DIMENSION(8), SAVE :: drow=(/1, 1, 0, -1, -1, -1, 0, 1/)
    INTEGER, DIMENSION(8), SAVE :: dkind=(/1, 2, 3, 4, 5, 6, 7, 8/)
    INTRINSIC REAL
    INTEGER :: branch
    IF (drained_area(row, col) .GT. 1) THEN
      DO i=1,8
        col_imd = col + dcol(i)
        row_imd = row + drow(i)
        IF (col_imd .GT. 0 .AND. col_imd .LE. ncol .AND. row_imd .GT. 0 &
&           .AND. row_imd .LE. nrow) THEN
          IF (flow(row_imd, col_imd) .EQ. dkind(i)) THEN
            CALL PUSHCONTROL2B(2)
          ELSE
            CALL PUSHCONTROL2B(1)
          END IF
        ELSE
          CALL PUSHCONTROL2B(0)
        END IF
      END DO
      qup_b = dt*qup_b/(0.001_sp*dx**2*REAL(drained_area(row, col)-1))
      DO i=8,1,-1
        CALL POPCONTROL2B(branch)
        IF (branch .NE. 0) THEN
          IF (branch .NE. 1) THEN
            row_imd = row + drow(i)
            col_imd = col + dcol(i)
            q_b(row_imd, col_imd) = q_b(row_imd, col_imd) + qup_b
          END IF
        END IF
      END DO
    END IF
  END SUBROUTINE UPSTREAM_DISCHARGE_B

  SUBROUTINE UPSTREAM_DISCHARGE(dt, dx, nrow, ncol, flow, drained_area, &
&   row, col, q, qup)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: dt, dx
    INTEGER, INTENT(IN) :: nrow, ncol, row, col
    INTEGER, DIMENSION(nrow, ncol), INTENT(IN) :: flow, drained_area
    REAL(sp), DIMENSION(nrow, ncol), INTENT(IN) :: q
    REAL(sp), INTENT(OUT) :: qup
    INTEGER :: i, row_imd, col_imd
    INTEGER, DIMENSION(8), SAVE :: dcol=(/0, -1, -1, -1, 0, 1, 1, 1/)
    INTEGER, DIMENSION(8), SAVE :: drow=(/1, 1, 0, -1, -1, -1, 0, 1/)
    INTEGER, DIMENSION(8), SAVE :: dkind=(/1, 2, 3, 4, 5, 6, 7, 8/)
    INTRINSIC REAL
    qup = 0._sp
    IF (drained_area(row, col) .GT. 1) THEN
      DO i=1,8
        col_imd = col + dcol(i)
        row_imd = row + drow(i)
        IF (col_imd .GT. 0 .AND. col_imd .LE. ncol .AND. row_imd .GT. 0 &
&           .AND. row_imd .LE. nrow) THEN
          IF (flow(row_imd, col_imd) .EQ. dkind(i)) qup = qup + q(&
&             row_imd, col_imd)
        END IF
      END DO
      qup = qup*dt/(0.001_sp*dx*dx*REAL(drained_area(row, col)-1))
    END IF
  END SUBROUTINE UPSTREAM_DISCHARGE

!  Differentiation of sparse_upstream_discharge in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: q qup
!   with respect to varying inputs: q
  SUBROUTINE SPARSE_UPSTREAM_DISCHARGE_B(dt, dx, nrow, ncol, nac, flow, &
&   drained_area, ind_sparse, row, col, q, q_b, qup, qup_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: dt, dx
    INTEGER, INTENT(IN) :: nrow, ncol, nac, row, col
    INTEGER, DIMENSION(nrow, ncol), INTENT(IN) :: flow, drained_area, &
&   ind_sparse
    REAL(sp), DIMENSION(nac), INTENT(IN) :: q
    REAL(sp), DIMENSION(nac) :: q_b
    REAL(sp) :: qup
    REAL(sp) :: qup_b
    INTEGER :: i, row_imd, col_imd, k
    INTEGER, DIMENSION(8), SAVE :: dcol=(/0, -1, -1, -1, 0, 1, 1, 1/)
    INTEGER, DIMENSION(8), SAVE :: drow=(/1, 1, 0, -1, -1, -1, 0, 1/)
    INTEGER, DIMENSION(8), SAVE :: dkind=(/1, 2, 3, 4, 5, 6, 7, 8/)
    INTRINSIC REAL
    INTEGER :: branch
    IF (drained_area(row, col) .GT. 1) THEN
      DO i=1,8
        col_imd = col + dcol(i)
        row_imd = row + drow(i)
        IF (col_imd .GT. 0 .AND. col_imd .LE. ncol .AND. row_imd .GT. 0 &
&           .AND. row_imd .LE. nrow) THEN
          IF (flow(row_imd, col_imd) .EQ. dkind(i)) THEN
            CALL PUSHCONTROL2B(2)
          ELSE
            CALL PUSHCONTROL2B(1)
          END IF
        ELSE
          CALL PUSHCONTROL2B(0)
        END IF
      END DO
      qup_b = dt*qup_b/(0.001_sp*dx**2*REAL(drained_area(row, col)-1))
      DO i=8,1,-1
        CALL POPCONTROL2B(branch)
        IF (branch .NE. 0) THEN
          IF (branch .NE. 1) THEN
            row_imd = row + drow(i)
            col_imd = col + dcol(i)
            k = ind_sparse(row_imd, col_imd)
            q_b(k) = q_b(k) + qup_b
          END IF
        END IF
      END DO
    END IF
  END SUBROUTINE SPARSE_UPSTREAM_DISCHARGE_B

  SUBROUTINE SPARSE_UPSTREAM_DISCHARGE(dt, dx, nrow, ncol, nac, flow, &
&   drained_area, ind_sparse, row, col, q, qup)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: dt, dx
    INTEGER, INTENT(IN) :: nrow, ncol, nac, row, col
    INTEGER, DIMENSION(nrow, ncol), INTENT(IN) :: flow, drained_area, &
&   ind_sparse
    REAL(sp), DIMENSION(nac), INTENT(IN) :: q
    REAL(sp), INTENT(OUT) :: qup
    INTEGER :: i, row_imd, col_imd, k
    INTEGER, DIMENSION(8), SAVE :: dcol=(/0, -1, -1, -1, 0, 1, 1, 1/)
    INTEGER, DIMENSION(8), SAVE :: drow=(/1, 1, 0, -1, -1, -1, 0, 1/)
    INTEGER, DIMENSION(8), SAVE :: dkind=(/1, 2, 3, 4, 5, 6, 7, 8/)
    INTRINSIC REAL
    qup = 0._sp
    IF (drained_area(row, col) .GT. 1) THEN
      DO i=1,8
        col_imd = col + dcol(i)
        row_imd = row + drow(i)
        IF (col_imd .GT. 0 .AND. col_imd .LE. ncol .AND. row_imd .GT. 0 &
&           .AND. row_imd .LE. nrow) THEN
          IF (flow(row_imd, col_imd) .EQ. dkind(i)) THEN
            k = ind_sparse(row_imd, col_imd)
            qup = qup + q(k)
          END IF
        END IF
      END DO
      qup = qup*dt/(0.001_sp*dx*dx*REAL(drained_area(row, col)-1))
    END IF
  END SUBROUTINE SPARSE_UPSTREAM_DISCHARGE

!  Differentiation of gr_transfer1 in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: hr qrout lr
!   with respect to varying inputs: qup hr lr
  SUBROUTINE GR_TRANSFER1_B(dt, qup, qup_b, lr, lr_b, hr, hr_b, qrout, &
&   qrout_b)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: dt
    REAL(sp), INTENT(IN) :: qup, lr
    REAL(sp) :: qup_b, lr_b
    REAL(sp), INTENT(INOUT) :: hr
    REAL(sp), INTENT(INOUT) :: hr_b
    REAL(sp) :: qrout
    REAL(sp) :: qrout_b
    REAL(sp) :: hr_imd
    REAL(sp) :: hr_imd_b
    INTRINSIC EXP
    REAL(sp) :: temp
    hr_imd = hr + qup
    temp = dt/(60._sp*lr)
    hr_b = hr_b - qrout_b
    hr_imd_b = qrout_b + EXP(-temp)*hr_b
    lr_b = lr_b + temp*EXP(-temp)*hr_imd*hr_b/lr
    hr_b = hr_imd_b
    qup_b = hr_imd_b
  END SUBROUTINE GR_TRANSFER1_B

  SUBROUTINE GR_TRANSFER1(dt, qup, lr, hr, qrout)
    IMPLICIT NONE
    REAL(sp), INTENT(IN) :: dt
    REAL(sp), INTENT(IN) :: qup, lr
    REAL(sp), INTENT(INOUT) :: hr
    REAL(sp), INTENT(OUT) :: qrout
    REAL(sp) :: hr_imd
    INTRINSIC EXP
    hr_imd = hr + qup
    hr = hr_imd*EXP(-(dt/(lr*60._sp)))
    qrout = hr_imd - hr
  END SUBROUTINE GR_TRANSFER1

END MODULE MD_OPERATOR_DIFF_B

SUBROUTINE FORWARD_NODIFF_B(setup, mesh, input_data, parameters, &
& parameters_bgd, states, states_bgd, output, cost)
!% =================================================================================================================== %!
!%   Module import ('only' is commented because of issues in adjoint model)
!% =================================================================================================================== %!
!% only: sp
  USE MWD_COMMON
!% only: SetupDT
  USE MWD_SETUP
!% only: MeshDT
  USE MWD_MESH
!% only: Input_DataDT
  USE MWD_INPUT_DATA
!% only: ParametersDT
  USE MWD_PARAMETERS_DIFF_B
!% only: StatesDT
  USE MWD_STATES_DIFF_B
!% only: OutputDT
  USE MWD_OUTPUT_DIFF_B
!% only: GR_interception, GR_production, GR_exchange, &
  USE MD_OPERATOR_DIFF_B
!% & GR_transferN, upstream_discharge, sparse_upstream_discharge, GR_transfer1
!% only: compute_cost
  USE MWD_COST_DIFF_B
  IMPLICIT NONE
!% =================================================================================================================== %!
!%   Derived Type Variables (shared)
!% =================================================================================================================== %!
  TYPE(SETUPDT), INTENT(IN) :: setup
  TYPE(MESHDT), INTENT(IN) :: mesh
  TYPE(INPUT_DATADT), INTENT(IN) :: input_data
  TYPE(PARAMETERSDT), INTENT(IN) :: parameters, parameters_bgd
  TYPE(STATESDT), INTENT(INOUT) :: states, states_bgd
  TYPE(OUTPUTDT), INTENT(INOUT) :: output
  REAL(sp), INTENT(INOUT) :: cost
!% =================================================================================================================== %!
!%   Local Variables (private)
!===================================================================================================================== %!
  TYPE(STATESDT) :: states_imd
  REAL(sp), DIMENSION(:, :), ALLOCATABLE :: q
  REAL(sp), DIMENSION(:), ALLOCATABLE :: sparse_q
  REAL(sp) :: prcp, pet, ei, pn, en, pr, perc, l, prr, prl, prd, qd, qr&
& , ql, qt, qup, qrout
  INTEGER :: t, i, row, col, k, g
  INTRINSIC MIN
  INTRINSIC MAX
  INTRINSIC REAL
  cost = 0._sp
  states_imd = states
  IF (setup%sparse_storage) THEN
    ALLOCATE(sparse_q(mesh%nac))
  ELSE
    ALLOCATE(q(mesh%nrow, mesh%ncol))
  END IF
!% =================================================================================================================== %!
!%   Begin subroutine
!% =================================================================================================================== %!
!% [ DO TIME ]
  DO t=1,setup%ntime_step
!% [ DO SPACE ]
    DO i=1,mesh%nrow*mesh%ncol
!% =============================================================================================================== %!
!%   Local Variables Initialisation for time step (t) and cell (i)
!% =============================================================================================================== %!
      ei = 0._sp
      pn = 0._sp
      en = 0._sp
      pr = 0._sp
      perc = 0._sp
      l = 0._sp
      prr = 0._sp
      prl = 0._sp
      prd = 0._sp
      qd = 0._sp
      qr = 0._sp
      ql = 0._sp
      qup = 0._sp
      qrout = 0._sp
!% [ END IF PATH ]
!% =========================================================================================================== %!
!%   Cell indice (i) to Cell indices (row, col) following an increasing order of drained area 
!% =========================================================================================================== %!
      IF (mesh%path(1, i) .GT. 0 .AND. mesh%path(2, i) .GT. 0) THEN
!% [ IF PATH ]
        row = mesh%path(1, i)
        col = mesh%path(2, i)
        IF (setup%sparse_storage) k = mesh%rowcol_to_ind_sparse(row, col&
&           )
!% [ END IF ACTIVE CELL ]
!% ======================================================================================================= %!
!%   Global/Local active cell
!% ======================================================================================================= %!
        IF (mesh%active_cell(row, col) .EQ. 1 .AND. mesh%&
&           local_active_cell(row, col) .EQ. 1) THEN
!% [ IF ACTIVE CELL ]
          IF (setup%sparse_storage) THEN
            prcp = input_data%sparse_prcp(k, t)
            pet = input_data%sparse_pet(k, t)
          ELSE
            prcp = input_data%prcp(row, col, t)
            pet = input_data%pet(row, col, t)
          END IF
!% [ END IF PRCP GAP ]
          IF (prcp .GE. 0 .AND. pet .GE. 0) THEN
!% [ IF PRCP GAP ]
!% =============================================================================================== %!
!%   Interception module case [ 0 - 1 ]
!% =============================================================================================== %!
            SELECT CASE  (setup%interception_module) 
            CASE (0) 
              IF (pet .GT. prcp) THEN
                ei = prcp
              ELSE
                ei = pet
              END IF
              IF (0._sp .LT. prcp - ei) THEN
                pn = prcp - ei
              ELSE
                pn = 0._sp
              END IF
            CASE (1) 
              CALL GR_INTERCEPTION(prcp, pet, parameters%ci(row, col), &
&                            states%hi(row, col), pn, ei)
            END SELECT
            en = pet - ei
!% =============================================================================================== %!
!%   Production module case [ 0 ]
!% =============================================================================================== %!
            SELECT CASE  (setup%production_module) 
            CASE (0) 
              CALL GR_PRODUCTION(pn, en, parameters%cp(row, col), &
&                          parameters%beta(row, col), states%hp(row, col&
&                          ), pr, perc)
            END SELECT
!% =============================================================================================== %!
!%   Exchange module case [ 0 - 1 ]
!% =============================================================================================== %!
            SELECT CASE  (setup%exchange_module) 
            CASE (0) 
              l = 0._sp
            CASE (1) 
              CALL GR_EXCHANGE(parameters%exc(row, col), states%hft(row&
&                        , col), l)
            END SELECT
          END IF
!% =================================================================================================== %!
!%   Transfer module case [ 0 ]
!% =================================================================================================== %!
          SELECT CASE  (setup%transfer_module) 
          CASE (0) 
            prr = parameters%alpha(row, col)*(pr+perc) + l
            prd = (1._sp-parameters%alpha(row, col))*(pr+perc)
            CALL GR_TRANSFERN(5._sp, prcp, prr, parameters%cft(row, col)&
&                       , states%hft(row, col), qr)
            IF (0._sp .LT. prd + l) THEN
              qd = prd + l
            ELSE
              qd = 0._sp
            END IF
          CASE (1) 
            prr = 0.9_sp*parameters%alpha(row, col)*(pr+perc) + l
            prl = 0.9_sp*(1._sp-parameters%alpha(row, col))*(pr+perc)
            prd = 0.1_sp*(pr+perc)
            CALL GR_TRANSFERN(5._sp, prcp, prr, parameters%cft(row, col)&
&                       , states%hft(row, col), qr)
            CALL GR_TRANSFERN(5._sp, prcp, prl, parameters%cst(row, col)&
&                       , states%hst(row, col), ql)
            IF (0._sp .LT. prd + l) THEN
              qd = prd + l
            ELSE
              qd = 0._sp
            END IF
          END SELECT
          qt = qd + qr + ql
!% =================================================================================================== %!
!%   Routing module case [ 0 - 1 ]
!% =================================================================================================== %!
          SELECT CASE  (setup%routing_module) 
          CASE (0) 
            IF (setup%sparse_storage) THEN
              CALL SPARSE_UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%&
&                                      nrow, mesh%ncol, mesh%nac, mesh%&
&                                      flow, mesh%drained_area, mesh%&
&                                      rowcol_to_ind_sparse, row, col, &
&                                      sparse_q, qup)
              sparse_q(k) = (qt+qup*REAL(mesh%drained_area(row, col)-1))&
&               *mesh%dx*mesh%dx*0.001_sp/setup%dt
            ELSE
              CALL UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%nrow, mesh&
&                               %ncol, mesh%flow, mesh%drained_area, row&
&                               , col, q, qup)
              q(row, col) = (qt+qup*REAL(mesh%drained_area(row, col)-1))&
&               *mesh%dx*mesh%dx*0.001_sp/setup%dt
            END IF
          CASE (1) 
            IF (setup%sparse_storage) THEN
              CALL SPARSE_UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%&
&                                      nrow, mesh%ncol, mesh%nac, mesh%&
&                                      flow, mesh%drained_area, mesh%&
&                                      rowcol_to_ind_sparse, row, col, &
&                                      sparse_q, qup)
              CALL GR_TRANSFER1(setup%dt, qup, parameters%lr(row, col), &
&                         states%hlr(row, col), qrout)
              sparse_q(k) = (qt+qrout*REAL(mesh%drained_area(row, col)-1&
&               ))*mesh%dx*mesh%dx*0.001_sp/setup%dt
            ELSE
              CALL UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%nrow, mesh&
&                               %ncol, mesh%flow, mesh%drained_area, row&
&                               , col, q, qup)
              CALL GR_TRANSFER1(setup%dt, qup, parameters%lr(row, col), &
&                         states%hlr(row, col), qrout)
              q(row, col) = (qt+qrout*REAL(mesh%drained_area(row, col)-1&
&               ))*mesh%dx*mesh%dx*0.001_sp/setup%dt
            END IF
          END SELECT
        END IF
      END IF
    END DO
!% [ END DO SPACE ]
!% =============================================================================================================== %!
!%   Store simulated discharge at gauge
!% =============================================================================================================== %!
    DO g=1,mesh%ng
      row = mesh%gauge_pos(1, g)
      col = mesh%gauge_pos(2, g)
      IF (setup%sparse_storage) THEN
        k = mesh%rowcol_to_ind_sparse(row, col)
        output%qsim(g, t) = sparse_q(k)
      ELSE
        output%qsim(g, t) = q(row, col)
      END IF
    END DO
!% =============================================================================================================== %!
!%   Store simulated discharge on domain (optional)
!% =============================================================================================================== %!
    IF (setup%save_qsim_domain) THEN
      IF (setup%sparse_storage) THEN
        output%sparse_qsim_domain(:, t) = sparse_q
      ELSE
        output%qsim_domain(:, :, t) = q
      END IF
    END IF
  END DO
!% [ END DO TIME ]
!% =============================================================================================================== %!
!%   Store states at final time step (optional)
!% =============================================================================================================== %!
  output%fstates = states
!% =================================================================================================================== %!
!%   Compute J
!% =================================================================================================================== %!
  CALL COMPUTE_COST(setup, mesh, input_data, parameters, parameters_bgd&
&             , states_imd, states_bgd, output, cost)
END SUBROUTINE FORWARD_NODIFF_B

!  Differentiation of forward in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: cost
!   with respect to varying inputs: *(parameters.ci) *(parameters.cp)
!                *(parameters.beta) *(parameters.cft) *(parameters.cst)
!                *(parameters.alpha) *(parameters.exc) *(parameters.lr)
!                *(states.hi) *(states.hp) *(states.hft) *(states.hst)
!                *(states.hlr) cost
!   RW status of diff variables: parameters.ci:(loc) *(parameters.ci):out
!                parameters.cp:(loc) *(parameters.cp):out parameters.beta:(loc)
!                *(parameters.beta):out parameters.cft:(loc) *(parameters.cft):out
!                parameters.cst:(loc) *(parameters.cst):out parameters.alpha:(loc)
!                *(parameters.alpha):out parameters.exc:(loc) *(parameters.exc):out
!                parameters.lr:(loc) *(parameters.lr):out *(output.qsim):(loc)
!                states.hi:(loc) *(states.hi):out states.hp:(loc)
!                *(states.hp):out states.hft:(loc) *(states.hft):out
!                states.hst:(loc) *(states.hst):out states.hlr:(loc)
!                *(states.hlr):out cost:in-zero
!   Plus diff mem management of: parameters.ci:in parameters.cp:in
!                parameters.beta:in parameters.cft:in parameters.cst:in
!                parameters.alpha:in parameters.exc:in parameters.lr:in
!                output.qsim:in states.hi:in states.hp:in states.hft:in
!                states.hst:in states.hlr:in
SUBROUTINE FORWARD_B(setup, mesh, input_data, parameters, parameters_b, &
& parameters_bgd, states, states_b, states_bgd, output, output_b, cost, &
& cost_b)
!% =================================================================================================================== %!
!%   Module import ('only' is commented because of issues in adjoint model)
!% =================================================================================================================== %!
!% only: sp
  USE MWD_COMMON
!% only: SetupDT
  USE MWD_SETUP
!% only: MeshDT
  USE MWD_MESH
!% only: Input_DataDT
  USE MWD_INPUT_DATA
!% only: ParametersDT
  USE MWD_PARAMETERS_DIFF_B
!% only: StatesDT
  USE MWD_STATES_DIFF_B
!% only: OutputDT
  USE MWD_OUTPUT_DIFF_B
!% only: GR_interception, GR_production, GR_exchange, &
  USE MD_OPERATOR_DIFF_B
!% & GR_transferN, upstream_discharge, sparse_upstream_discharge, GR_transfer1
!% only: compute_cost
  USE MWD_COST_DIFF_B
  IMPLICIT NONE
!% =================================================================================================================== %!
!%   Derived Type Variables (shared)
!% =================================================================================================================== %!
  TYPE(SETUPDT), INTENT(IN) :: setup
  TYPE(MESHDT), INTENT(IN) :: mesh
  TYPE(INPUT_DATADT), INTENT(IN) :: input_data
  TYPE(PARAMETERSDT), INTENT(IN) :: parameters, parameters_bgd
  TYPE(PARAMETERSDT) :: parameters_b
  TYPE(STATESDT), INTENT(INOUT) :: states, states_bgd
  TYPE(STATESDT), INTENT(INOUT) :: states_b
  TYPE(OUTPUTDT), INTENT(INOUT) :: output
  TYPE(OUTPUTDT_DIFF_B), INTENT(INOUT) :: output_b
  REAL(sp), INTENT(INOUT) :: cost
  REAL(sp), INTENT(INOUT) :: cost_b
!% =================================================================================================================== %!
!%   Local Variables (private)
!===================================================================================================================== %!
  TYPE(STATESDT) :: states_imd
  TYPE(STATESDT) :: states_imd_b
  REAL(sp), DIMENSION(:, :), ALLOCATABLE :: q
  REAL(sp), DIMENSION(:, :), ALLOCATABLE :: q_b
  REAL(sp), DIMENSION(:), ALLOCATABLE :: sparse_q
  REAL(sp), DIMENSION(:), ALLOCATABLE :: sparse_q_b
  REAL(sp) :: prcp, pet, ei, pn, en, pr, perc, l, prr, prl, prd, qd, qr&
& , ql, qt, qup, qrout
  REAL(sp) :: ei_b, pn_b, en_b, pr_b, perc_b, l_b, prr_b, prl_b, prd_b, &
& qd_b, qr_b, ql_b, qt_b, qup_b, qrout_b
  INTEGER :: t, i, row, col, k, g
  INTRINSIC MIN
  INTRINSIC MAX
  INTRINSIC REAL
  REAL(sp) :: temp_b
  REAL*4 :: temp_b0
  INTEGER :: branch
  states_imd_b = states_b
  states_imd = states
  IF (setup%sparse_storage) THEN
    ALLOCATE(sparse_q_b(mesh%nac))
    sparse_q_b = 0.0_4
    ALLOCATE(sparse_q(mesh%nac))
    CALL PUSHCONTROL1B(1)
  ELSE
    ALLOCATE(q_b(mesh%nrow, mesh%ncol))
    q_b = 0.0_4
    ALLOCATE(q(mesh%nrow, mesh%ncol))
    CALL PUSHCONTROL1B(0)
  END IF
!% =================================================================================================================== %!
!%   Begin subroutine
!% =================================================================================================================== %!
!% [ DO TIME ]
  DO t=1,setup%ntime_step
!% [ DO SPACE ]
    DO i=1,mesh%nrow*mesh%ncol
!% =============================================================================================================== %!
!%   Local Variables Initialisation for time step (t) and cell (i)
!% =============================================================================================================== %!
      ei = 0._sp
      CALL PUSHREAL4(pn)
      pn = 0._sp
      CALL PUSHREAL4(pr)
      pr = 0._sp
      CALL PUSHREAL4(perc)
      perc = 0._sp
      l = 0._sp
      qd = 0._sp
      qr = 0._sp
      ql = 0._sp
!% [ END IF PATH ]
!% =========================================================================================================== %!
!%   Cell indice (i) to Cell indices (row, col) following an increasing order of drained area 
!% =========================================================================================================== %!
      IF (mesh%path(1, i) .GT. 0 .AND. mesh%path(2, i) .GT. 0) THEN
!% [ IF PATH ]
        CALL PUSHINTEGER4(row)
        row = mesh%path(1, i)
        CALL PUSHINTEGER4(col)
        col = mesh%path(2, i)
        IF (setup%sparse_storage) THEN
          CALL PUSHINTEGER4(k)
          k = mesh%rowcol_to_ind_sparse(row, col)
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
!% [ END IF ACTIVE CELL ]
!% ======================================================================================================= %!
!%   Global/Local active cell
!% ======================================================================================================= %!
        IF (mesh%active_cell(row, col) .EQ. 1 .AND. mesh%&
&           local_active_cell(row, col) .EQ. 1) THEN
!% [ IF ACTIVE CELL ]
          IF (setup%sparse_storage) THEN
            CALL PUSHREAL4(prcp)
            prcp = input_data%sparse_prcp(k, t)
            CALL PUSHREAL4(pet)
            pet = input_data%sparse_pet(k, t)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHREAL4(prcp)
            prcp = input_data%prcp(row, col, t)
            CALL PUSHREAL4(pet)
            pet = input_data%pet(row, col, t)
            CALL PUSHCONTROL1B(1)
          END IF
!% [ END IF PRCP GAP ]
          IF (prcp .GE. 0 .AND. pet .GE. 0) THEN
!% [ IF PRCP GAP ]
!% =============================================================================================== %!
!%   Interception module case [ 0 - 1 ]
!% =============================================================================================== %!
            SELECT CASE  (setup%interception_module) 
            CASE (0) 
              IF (pet .GT. prcp) THEN
                ei = prcp
              ELSE
                ei = pet
              END IF
              IF (0._sp .LT. prcp - ei) THEN
                CALL PUSHCONTROL2B(2)
                pn = prcp - ei
              ELSE
                CALL PUSHCONTROL2B(2)
                pn = 0._sp
              END IF
            CASE (1) 
              CALL PUSHREAL4(states%hi(row, col))
              CALL GR_INTERCEPTION(prcp, pet, parameters%ci(row, col), &
&                            states%hi(row, col), pn, ei)
              CALL PUSHCONTROL2B(1)
            CASE DEFAULT
              CALL PUSHCONTROL2B(0)
            END SELECT
            CALL PUSHREAL4(en)
            en = pet - ei
!% =============================================================================================== %!
!%   Production module case [ 0 ]
!% =============================================================================================== %!
            SELECT CASE  (setup%production_module) 
            CASE (0) 
              CALL PUSHREAL4(states%hp(row, col))
              CALL GR_PRODUCTION(pn, en, parameters%cp(row, col), &
&                          parameters%beta(row, col), states%hp(row, col&
&                          ), pr, perc)
              CALL PUSHCONTROL1B(1)
            CASE DEFAULT
              CALL PUSHCONTROL1B(0)
            END SELECT
!% =============================================================================================== %!
!%   Exchange module case [ 0 - 1 ]
!% =============================================================================================== %!
            SELECT CASE  (setup%exchange_module) 
            CASE (0) 
              CALL PUSHCONTROL2B(0)
              l = 0._sp
            CASE (1) 
              CALL GR_EXCHANGE(parameters%exc(row, col), states%hft(row&
&                        , col), l)
              CALL PUSHCONTROL2B(1)
            CASE DEFAULT
              CALL PUSHCONTROL2B(0)
            END SELECT
          ELSE
            CALL PUSHCONTROL2B(2)
          END IF
!% =================================================================================================== %!
!%   Transfer module case [ 0 ]
!% =================================================================================================== %!
          SELECT CASE  (setup%transfer_module) 
          CASE (0) 
            CALL PUSHREAL4(prr)
            prr = parameters%alpha(row, col)*(pr+perc) + l
            prd = (1._sp-parameters%alpha(row, col))*(pr+perc)
            CALL PUSHREAL4(states%hft(row, col))
            CALL GR_TRANSFERN(5._sp, prcp, prr, parameters%cft(row, col)&
&                       , states%hft(row, col), qr)
            IF (0._sp .LT. prd + l) THEN
              qd = prd + l
              CALL PUSHCONTROL3B(2)
            ELSE
              qd = 0._sp
              CALL PUSHCONTROL3B(1)
            END IF
          CASE (1) 
            CALL PUSHREAL4(prr)
            prr = 0.9_sp*parameters%alpha(row, col)*(pr+perc) + l
            prl = 0.9_sp*(1._sp-parameters%alpha(row, col))*(pr+perc)
            prd = 0.1_sp*(pr+perc)
            CALL PUSHREAL4(states%hft(row, col))
            CALL GR_TRANSFERN(5._sp, prcp, prr, parameters%cft(row, col)&
&                       , states%hft(row, col), qr)
            CALL PUSHREAL4(states%hst(row, col))
            CALL GR_TRANSFERN(5._sp, prcp, prl, parameters%cst(row, col)&
&                       , states%hst(row, col), ql)
            IF (0._sp .LT. prd + l) THEN
              qd = prd + l
              CALL PUSHCONTROL3B(4)
            ELSE
              qd = 0._sp
              CALL PUSHCONTROL3B(3)
            END IF
          CASE DEFAULT
            CALL PUSHCONTROL3B(0)
          END SELECT
          qt = qd + qr + ql
!% =================================================================================================== %!
!%   Routing module case [ 0 - 1 ]
!% =================================================================================================== %!
          SELECT CASE  (setup%routing_module) 
          CASE (0) 
            IF (setup%sparse_storage) THEN
              CALL PUSHREAL4(qup)
              CALL SPARSE_UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%&
&                                      nrow, mesh%ncol, mesh%nac, mesh%&
&                                      flow, mesh%drained_area, mesh%&
&                                      rowcol_to_ind_sparse, row, col, &
&                                      sparse_q, qup)
              sparse_q(k) = (qt+qup*REAL(mesh%drained_area(row, col)-1))&
&               *mesh%dx*mesh%dx*0.001_sp/setup%dt
              CALL PUSHCONTROL3B(5)
            ELSE
              CALL PUSHREAL4(qup)
              CALL UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%nrow, mesh&
&                               %ncol, mesh%flow, mesh%drained_area, row&
&                               , col, q, qup)
              q(row, col) = (qt+qup*REAL(mesh%drained_area(row, col)-1))&
&               *mesh%dx*mesh%dx*0.001_sp/setup%dt
              CALL PUSHCONTROL3B(4)
            END IF
          CASE (1) 
            IF (setup%sparse_storage) THEN
              CALL PUSHREAL4(qup)
              CALL SPARSE_UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%&
&                                      nrow, mesh%ncol, mesh%nac, mesh%&
&                                      flow, mesh%drained_area, mesh%&
&                                      rowcol_to_ind_sparse, row, col, &
&                                      sparse_q, qup)
              CALL PUSHREAL4(states%hlr(row, col))
              CALL GR_TRANSFER1(setup%dt, qup, parameters%lr(row, col), &
&                         states%hlr(row, col), qrout)
              sparse_q(k) = (qt+qrout*REAL(mesh%drained_area(row, col)-1&
&               ))*mesh%dx*mesh%dx*0.001_sp/setup%dt
              CALL PUSHCONTROL3B(3)
            ELSE
              CALL PUSHREAL4(qup)
              CALL UPSTREAM_DISCHARGE(setup%dt, mesh%dx, mesh%nrow, mesh&
&                               %ncol, mesh%flow, mesh%drained_area, row&
&                               , col, q, qup)
              CALL PUSHREAL4(states%hlr(row, col))
              CALL GR_TRANSFER1(setup%dt, qup, parameters%lr(row, col), &
&                         states%hlr(row, col), qrout)
              q(row, col) = (qt+qrout*REAL(mesh%drained_area(row, col)-1&
&               ))*mesh%dx*mesh%dx*0.001_sp/setup%dt
              CALL PUSHCONTROL3B(2)
            END IF
          CASE DEFAULT
            CALL PUSHCONTROL3B(6)
          END SELECT
        ELSE
          CALL PUSHCONTROL3B(1)
        END IF
      ELSE
        CALL PUSHCONTROL3B(0)
      END IF
    END DO
!% [ END DO SPACE ]
!% =============================================================================================================== %!
!%   Store simulated discharge at gauge
!% =============================================================================================================== %!
    DO g=1,mesh%ng
      CALL PUSHINTEGER4(row)
      row = mesh%gauge_pos(1, g)
      CALL PUSHINTEGER4(col)
      col = mesh%gauge_pos(2, g)
      IF (setup%sparse_storage) THEN
        CALL PUSHINTEGER4(k)
        k = mesh%rowcol_to_ind_sparse(row, col)
        output%qsim(g, t) = sparse_q(k)
        CALL PUSHCONTROL1B(1)
      ELSE
        output%qsim(g, t) = q(row, col)
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
  END DO
  CALL COMPUTE_COST(setup, mesh, input_data, parameters, parameters_bgd, states_imd, states_bgd, output, cost)
  CALL SET0_PARAMETERS(parameters_b)
  CALL SET0_STATES(states_b)
  CALL SET0_STATES(states_imd_b)
  CALL COMPUTE_COST_B(setup, mesh, input_data, parameters, parameters_b&
&               , parameters_bgd, states_imd, states_imd_b, states_bgd, &
&               output, output_b, cost, cost_b)
  DO t=setup%ntime_step,1,-1
    DO g=mesh%ng,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        row = mesh%gauge_pos(1, g)
        col = mesh%gauge_pos(2, g)
        q_b(row, col) = q_b(row, col) + output_b%qsim(g, t)
        output_b%qsim(g, t) = 0.0_4
      ELSE
        sparse_q_b(k) = sparse_q_b(k) + output_b%qsim(g, t)
        output_b%qsim(g, t) = 0.0_4
        CALL POPINTEGER4(k)
      END IF
      CALL POPINTEGER4(col)
      CALL POPINTEGER4(row)
    END DO
    DO i=mesh%nrow*mesh%ncol,1,-1
      CALL POPCONTROL3B(branch)
      IF (branch .LT. 3) THEN
        IF (branch .EQ. 0) THEN
          GOTO 130
        ELSE IF (branch .EQ. 1) THEN
          GOTO 120
        ELSE
          row = mesh%path(1, i)
          col = mesh%path(2, i)
          temp_b0 = mesh%dx**2*0.001_sp*q_b(row, col)/setup%dt
          q_b(row, col) = 0.0_4
          qt_b = temp_b0
          qrout_b = REAL(mesh%drained_area(row, col)-1)*temp_b0
          CALL POPREAL4(states%hlr(row, col))
          CALL GR_TRANSFER1_B(setup%dt, qup, qup_b, parameters%lr(row, &
&                       col), parameters_b%lr(row, col), states%hlr(row&
&                       , col), states_b%hlr(row, col), qrout, qrout_b)
          CALL POPREAL4(qup)
          CALL UPSTREAM_DISCHARGE_B(setup%dt, mesh%dx, mesh%nrow, mesh%&
&                             ncol, mesh%flow, mesh%drained_area, row, &
&                             col, q, q_b, qup, qup_b)
        END IF
      ELSE IF (branch .LT. 5) THEN
        IF (branch .EQ. 3) THEN
          row = mesh%path(1, i)
          col = mesh%path(2, i)
          temp_b0 = mesh%dx**2*0.001_sp*sparse_q_b(k)/setup%dt
          sparse_q_b(k) = 0.0_4
          qt_b = temp_b0
          qrout_b = REAL(mesh%drained_area(row, col)-1)*temp_b0
          CALL POPREAL4(states%hlr(row, col))
          CALL GR_TRANSFER1_B(setup%dt, qup, qup_b, parameters%lr(row, &
&                       col), parameters_b%lr(row, col), states%hlr(row&
&                       , col), states_b%hlr(row, col), qrout, qrout_b)
          CALL POPREAL4(qup)
          CALL SPARSE_UPSTREAM_DISCHARGE_B(setup%dt, mesh%dx, mesh%nrow&
&                                    , mesh%ncol, mesh%nac, mesh%flow, &
&                                    mesh%drained_area, mesh%&
&                                    rowcol_to_ind_sparse, row, col, &
&                                    sparse_q, sparse_q_b, qup, qup_b)
        ELSE
          row = mesh%path(1, i)
          col = mesh%path(2, i)
          temp_b0 = mesh%dx**2*0.001_sp*q_b(row, col)/setup%dt
          q_b(row, col) = 0.0_4
          qt_b = temp_b0
          qup_b = REAL(mesh%drained_area(row, col)-1)*temp_b0
          CALL POPREAL4(qup)
          CALL UPSTREAM_DISCHARGE_B(setup%dt, mesh%dx, mesh%nrow, mesh%&
&                             ncol, mesh%flow, mesh%drained_area, row, &
&                             col, q, q_b, qup, qup_b)
        END IF
      ELSE IF (branch .EQ. 5) THEN
        row = mesh%path(1, i)
        col = mesh%path(2, i)
        temp_b0 = mesh%dx**2*0.001_sp*sparse_q_b(k)/setup%dt
        sparse_q_b(k) = 0.0_4
        qt_b = temp_b0
        qup_b = REAL(mesh%drained_area(row, col)-1)*temp_b0
        CALL POPREAL4(qup)
        CALL SPARSE_UPSTREAM_DISCHARGE_B(setup%dt, mesh%dx, mesh%nrow, &
&                                  mesh%ncol, mesh%nac, mesh%flow, mesh%&
&                                  drained_area, mesh%&
&                                  rowcol_to_ind_sparse, row, col, &
&                                  sparse_q, sparse_q_b, qup, qup_b)
      ELSE
        qt_b = 0.0_4
      END IF
      qd_b = qt_b
      qr_b = qt_b
      ql_b = qt_b
      CALL POPCONTROL3B(branch)
      IF (branch .LT. 2) THEN
        IF (branch .EQ. 0) THEN
          l_b = 0.0_4
          perc_b = 0.0_4
          pr_b = 0.0_4
          GOTO 100
        ELSE
          l_b = 0.0_4
          prd_b = 0.0_4
        END IF
      ELSE IF (branch .EQ. 2) THEN
        prd_b = qd_b
        l_b = qd_b
      ELSE
        IF (branch .EQ. 3) THEN
          l_b = 0.0_4
          prd_b = 0.0_4
        ELSE
          prd_b = qd_b
          l_b = qd_b
        END IF
        prl = 0.9_sp*(1._sp-parameters%alpha(row, col))*(pr+perc)
        CALL POPREAL4(states%hst(row, col))
        CALL GR_TRANSFERN_B(5._sp, prcp, prl, prl_b, parameters%cst(row&
&                     , col), parameters_b%cst(row, col), states%hst(row&
&                     , col), states_b%hst(row, col), ql, ql_b)
        CALL POPREAL4(states%hft(row, col))
        CALL GR_TRANSFERN_B(5._sp, prcp, prr, prr_b, parameters%cft(row&
&                     , col), parameters_b%cft(row, col), states%hft(row&
&                     , col), states_b%hft(row, col), qr, qr_b)
        parameters_b%alpha(row, col) = parameters_b%alpha(row, col) + (&
&         pr+perc)*0.9_sp*prr_b - (pr+perc)*0.9_sp*prl_b
        temp_b = (1._sp-parameters%alpha(row, col))*0.9_sp*prl_b
        pr_b = 0.1_sp*prd_b + temp_b
        perc_b = 0.1_sp*prd_b + temp_b
        CALL POPREAL4(prr)
        temp_b = parameters%alpha(row, col)*0.9_sp*prr_b
        l_b = l_b + prr_b
        pr_b = pr_b + temp_b
        perc_b = perc_b + temp_b
        GOTO 100
      END IF
      CALL POPREAL4(states%hft(row, col))
      CALL GR_TRANSFERN_B(5._sp, prcp, prr, prr_b, parameters%cft(row, &
&                   col), parameters_b%cft(row, col), states%hft(row, &
&                   col), states_b%hft(row, col), qr, qr_b)
      parameters_b%alpha(row, col) = parameters_b%alpha(row, col) + (pr+&
&       perc)*prr_b - (pr+perc)*prd_b
      temp_b = (1._sp-parameters%alpha(row, col))*prd_b
      pr_b = temp_b
      perc_b = temp_b
      CALL POPREAL4(prr)
      temp_b = parameters%alpha(row, col)*prr_b
      l_b = l_b + prr_b
      pr_b = pr_b + temp_b
      perc_b = perc_b + temp_b
 100  CALL POPCONTROL2B(branch)
      IF (branch .NE. 0) THEN
        IF (branch .EQ. 1) THEN
          CALL GR_EXCHANGE_B(parameters%exc(row, col), parameters_b%exc(&
&                      row, col), states%hft(row, col), states_b%hft(row&
&                      , col), l, l_b)
        ELSE
          GOTO 110
        END IF
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        en_b = 0.0_4
        pn_b = 0.0_4
      ELSE
        CALL POPREAL4(states%hp(row, col))
        CALL GR_PRODUCTION_B(pn, pn_b, en, en_b, parameters%cp(row, col)&
&                      , parameters_b%cp(row, col), parameters%beta(row&
&                      , col), parameters_b%beta(row, col), states%hp(&
&                      row, col), states_b%hp(row, col), pr, pr_b, perc&
&                      , perc_b)
      END IF
      CALL POPREAL4(en)
      ei_b = -en_b
      CALL POPCONTROL2B(branch)
      IF (branch .NE. 0) THEN
        IF (branch .EQ. 1) THEN
          CALL POPREAL4(states%hi(row, col))
          CALL GR_INTERCEPTION_B(prcp, pet, parameters%ci(row, col), &
&                          parameters_b%ci(row, col), states%hi(row, col&
&                          ), states_b%hi(row, col), pn, pn_b, ei, ei_b)
        END IF
      END IF
 110  CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL4(pet)
        CALL POPREAL4(prcp)
      ELSE
        CALL POPREAL4(pet)
        CALL POPREAL4(prcp)
      END IF
 120  CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) CALL POPINTEGER4(k)
      CALL POPINTEGER4(col)
      CALL POPINTEGER4(row)
 130  CALL POPREAL4(perc)
      CALL POPREAL4(pr)
      CALL POPREAL4(pn)
    END DO
  END DO
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DEALLOCATE(q)
    DEALLOCATE(q_b)
  ELSE
    DEALLOCATE(sparse_q)
    DEALLOCATE(sparse_q_b)
  END IF
  cost_b = 0.0_4
END SUBROUTINE FORWARD_B

