import pathlib

if __name__ == "__main__":
    solver_path = pathlib.Path("../smash/fcore/")

    solver_wrap_files = sorted(
        list(solver_path.glob("*/mwd_*.f90")) + list(solver_path.glob("*/mw_*.f90"))
    )

    with open("py_mod_names", "w") as f:
        f.write(
            "#% This file is automatically generated by gen_py_mod_names.py" + 2 * "\n"
        )
        f.write("{\n")

        for swf in solver_wrap_files:
            f.write(f'\t"{swf.stem}": "_{swf.stem}",\n')

        f.write("}")
