!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!%    This module `m_parameters` encapsulates all SMASH parameters
MODULE M_PARAMETERS_DIFF
  USE M_COMMON, ONLY : sp, dp, lchar, np, ns
  USE M_SETUP, ONLY : setupdt
  USE M_MESH, ONLY : meshdt
  IMPLICIT NONE
  PUBLIC :: parametersdt, parameters_derived_type_to_matrix, &
& matrix_to_parameters_derived_type, vector_to_parameters_derived_type
  TYPE PARAMETERSDT
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: cp
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: cft
      REAL(sp), DIMENSION(:, :), ALLOCATABLE :: lr
  END TYPE PARAMETERSDT

CONTAINS
  SUBROUTINE PARAMETERSDT_INITIALISE(parameters, setup, mesh)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    INTEGER :: nrow, ncol
    nrow = mesh%nrow
    ncol = mesh%ncol
    ALLOCATE(parameters%cp(nrow, ncol))
    ALLOCATE(parameters%cft(nrow, ncol))
    ALLOCATE(parameters%lr(nrow, ncol))
    CALL VECTOR_TO_PARAMETERS_DERIVED_TYPE(setup%default_parameters, &
&                                    parameters)
  END SUBROUTINE PARAMETERSDT_INITIALISE

  SUBROUTINE PARAMETERS_DERIVED_TYPE_TO_MATRIX(parameters, matrix)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(parameters%cp, 1), SIZE(parameters%cp, 2), &
&   np), INTENT(INOUT) :: matrix
    matrix(:, :, 1) = parameters%cp(:, :)
    matrix(:, :, 2) = parameters%cft(:, :)
    matrix(:, :, 3) = parameters%lr(:, :)
  END SUBROUTINE PARAMETERS_DERIVED_TYPE_TO_MATRIX

  SUBROUTINE MATRIX_TO_PARAMETERS_DERIVED_TYPE(matrix, parameters)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    INTRINSIC SIZE
    REAL(sp), DIMENSION(SIZE(parameters%cp, 1), SIZE(parameters%cp, 2), &
&   np), INTENT(IN) :: matrix
    parameters%cp(:, :) = matrix(:, :, 1)
    parameters%cft(:, :) = matrix(:, :, 2)
    parameters%lr(:, :) = matrix(:, :, 3)
  END SUBROUTINE MATRIX_TO_PARAMETERS_DERIVED_TYPE

  SUBROUTINE VECTOR_TO_PARAMETERS_DERIVED_TYPE(vector, parameters)
    IMPLICIT NONE
    TYPE(PARAMETERSDT), INTENT(INOUT) :: parameters
    REAL(sp), DIMENSION(np), INTENT(IN) :: vector
    parameters%cp = vector(1)
    parameters%cft = vector(2)
    parameters%lr = vector(3)
  END SUBROUTINE VECTOR_TO_PARAMETERS_DERIVED_TYPE

END MODULE M_PARAMETERS_DIFF

MODULE M_RUN_DIFF
  USE M_COMMON, ONLY : sp, dp, lchar, np, ns
  USE M_SETUP, ONLY : setupdt
  USE M_MESH, ONLY : meshdt
  USE M_INPUT_DATA, ONLY : input_datadt
  USE M_PARAMETERS_DIFF, ONLY : parametersdt, parametersdt_diff
  USE M_STATES, ONLY : statesdt
  USE M_OUTPUT, ONLY : outputdt
  IMPLICIT NONE
!~     subroutine run_ADJ()
!~     end subroutine run_ADJ
!~     subroutine run_TLM()
!~     end subroutine run_TLM

CONTAINS
!  Differentiation of run_direct in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: cost
!   with respect to varying inputs: *(parameters.cp)
!   RW status of diff variables: parameters.cp:(loc) *(parameters.cp):out
!                parameters.cft:(loc) *(parameters.cft):(loc) parameters.lr:(loc)
!                *(parameters.lr):(loc) cost:in-killed
!   Plus diff mem management of: parameters.cp:in
  SUBROUTINE RUN_DIRECT_B(setup, mesh, input_data, parameters, &
&   parametersb, states, output, cost, costb)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(INPUT_DATADT), INTENT(IN) :: input_data
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters
    TYPE(PARAMETERSDT) :: parametersb
    TYPE(STATESDT), INTENT(IN) :: states
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    REAL(sp), INTENT(INOUT) :: cost
    REAL(sp), INTENT(INOUT) :: costb
    INTRINSIC SUM
    parametersb%cp = 0.0_4
    parametersb%cp = parametersb%cp + costb
    parametersb%cft = 0.0_4
    parametersb%lr = 0.0_4
  END SUBROUTINE RUN_DIRECT_B

  SUBROUTINE RUN_DIRECT(setup, mesh, input_data, parameters, states, &
&   output, cost)
    IMPLICIT NONE
    TYPE(SETUPDT), INTENT(IN) :: setup
    TYPE(MESHDT), INTENT(IN) :: mesh
    TYPE(INPUT_DATADT), INTENT(IN) :: input_data
    TYPE(PARAMETERSDT), INTENT(IN) :: parameters
    TYPE(STATESDT), INTENT(IN) :: states
    TYPE(OUTPUTDT), INTENT(INOUT) :: output
    REAL(sp), INTENT(INOUT) :: cost
    INTRINSIC SUM
    cost = SUM(parameters%cp)
  END SUBROUTINE RUN_DIRECT

END MODULE M_RUN_DIFF

