# This workflow will compare tapenade file.
name: Tapenade Comparison

on:

    push:
        branches:
        - main

    pull_request:
        branches:
        - main
        - maintenance/**
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        
jobs:
    ubuntu:
        name: (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-20.04", "ubuntu-22.04"]

        steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            sudo apt-get update -y
            sudo apt-get install build-essential make openjdk-11-jre-headless

        - name: Compare
          run: |
            make tap-cmp
